# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.theme_update_input import ThemeUpdateInput

class TestThemeUpdateInput(unittest.TestCase):
    """ThemeUpdateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThemeUpdateInput:
        """Test ThemeUpdateInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThemeUpdateInput`
        """
        model = ThemeUpdateInput()
        if include_optional:
            return ThemeUpdateInput(
                name = 'Light Theme',
                config = {primaryColor=#ffffff, secondaryColor=#f0f0f0, fontFamily=Inter},
                is_active = True
            )
        else:
            return ThemeUpdateInput(
        )
        """

    def testThemeUpdateInput(self):
        """Test ThemeUpdateInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
