# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_status200_response_data_limits import GetRateLimitStatus200ResponseDataLimits

class TestGetRateLimitStatus200ResponseDataLimits(unittest.TestCase):
    """GetRateLimitStatus200ResponseDataLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitStatus200ResponseDataLimits:
        """Test GetRateLimitStatus200ResponseDataLimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitStatus200ResponseDataLimits`
        """
        model = GetRateLimitStatus200ResponseDataLimits()
        if include_optional:
            return GetRateLimitStatus200ResponseDataLimits(
                hourly_limit = 56,
                daily_limit = 56,
                monthly_limit = 56,
                burst_limit = 56,
                concurrent_limit = 56
            )
        else:
            return GetRateLimitStatus200ResponseDataLimits(
        )
        """

    def testGetRateLimitStatus200ResponseDataLimits(self):
        """Test GetRateLimitStatus200ResponseDataLimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
