# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.create_plan201_response import CreatePlan201Response

class TestCreatePlan201Response(unittest.TestCase):
    """CreatePlan201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePlan201Response:
        """Test CreatePlan201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePlan201Response`
        """
        model = CreatePlan201Response()
        if include_optional:
            return CreatePlan201Response(
                success = True,
                data = subtrackr_sdk.models.plan.Plan(
                    id = 'plan_premium', 
                    name = 'Premium Plan', 
                    price = 29.99, 
                    currency = 'USD', 
                    billing_cycle = 'monthly', 
                    features = [Unlimited subscriptions, Advanced analytics], 
                    is_active = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                request_id = 'req_abc123'
            )
        else:
            return CreatePlan201Response(
        )
        """

    def testCreatePlan201Response(self):
        """Test CreatePlan201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
