# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.purge_user_cache200_response import PurgeUserCache200Response

class TestPurgeUserCache200Response(unittest.TestCase):
    """PurgeUserCache200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PurgeUserCache200Response:
        """Test PurgeUserCache200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PurgeUserCache200Response`
        """
        model = PurgeUserCache200Response()
        if include_optional:
            return PurgeUserCache200Response(
                success = True,
                request_id = 'req_abc123'
            )
        else:
            return PurgeUserCache200Response(
        )
        """

    def testPurgeUserCache200Response(self):
        """Test PurgeUserCache200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
