# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.feature_update_input import FeatureUpdateInput

class TestFeatureUpdateInput(unittest.TestCase):
    """FeatureUpdateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureUpdateInput:
        """Test FeatureUpdateInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeatureUpdateInput`
        """
        model = FeatureUpdateInput()
        if include_optional:
            return FeatureUpdateInput(
                enabled = True
            )
        else:
            return FeatureUpdateInput(
                enabled = True,
        )
        """

    def testFeatureUpdateInput(self):
        """Test FeatureUpdateInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
