# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.api.plans_api import PlansApi


class TestPlansApi(unittest.TestCase):
    """PlansApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlansApi()

    def tearDown(self) -> None:
        pass

    def test_create_plan(self) -> None:
        """Test case for create_plan

        Create a new subscription plan
        """
        pass

    def test_deactivate_plan(self) -> None:
        """Test case for deactivate_plan

        Deactivate a plan
        """
        pass

    def test_get_plan_by_id(self) -> None:
        """Test case for get_plan_by_id

        Get a plan by ID
        """
        pass

    def test_list_plans(self) -> None:
        """Test case for list_plans

        List all subscription plans
        """
        pass

    def test_update_plan(self) -> None:
        """Test case for update_plan

        Update a plan
        """
        pass


if __name__ == '__main__':
    unittest.main()
