# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.delete_theme200_response_data import DeleteTheme200ResponseData

class TestDeleteTheme200ResponseData(unittest.TestCase):
    """DeleteTheme200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteTheme200ResponseData:
        """Test DeleteTheme200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteTheme200ResponseData`
        """
        model = DeleteTheme200ResponseData()
        if include_optional:
            return DeleteTheme200ResponseData(
                deleted = True
            )
        else:
            return DeleteTheme200ResponseData(
        )
        """

    def testDeleteTheme200ResponseData(self):
        """Test DeleteTheme200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
