# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.create_theme201_response import CreateTheme201Response

class TestCreateTheme201Response(unittest.TestCase):
    """CreateTheme201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTheme201Response:
        """Test CreateTheme201Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTheme201Response`
        """
        model = CreateTheme201Response()
        if include_optional:
            return CreateTheme201Response(
                success = True,
                data = subtrackr_sdk.models.theme.Theme(
                    id = 'theme_dark', 
                    merchant_id = 'merchant_123', 
                    name = 'Dark Theme', 
                    config = {primaryColor=#1a1a2e, secondaryColor=#16213e, fontFamily=Inter}, 
                    is_active = True, 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), ),
                request_id = 'req_abc123'
            )
        else:
            return CreateTheme201Response(
        )
        """

    def testCreateTheme201Response(self):
        """Test CreateTheme201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
