# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.api.rate_limits_api import RateLimitsApi


class TestRateLimitsApi(unittest.TestCase):
    """RateLimitsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RateLimitsApi()

    def tearDown(self) -> None:
        pass

    def test_get_rate_limit_analytics(self) -> None:
        """Test case for get_rate_limit_analytics

        Get rate limit analytics
        """
        pass

    def test_get_rate_limit_status(self) -> None:
        """Test case for get_rate_limit_status

        Get rate limit status for an API key
        """
        pass

    def test_manage_bypass(self) -> None:
        """Test case for manage_bypass

        Manage bypass list
        """
        pass

    def test_set_custom_rate_limits(self) -> None:
        """Test case for set_custom_rate_limits

        Set custom rate limits for an API key
        """
        pass


if __name__ == '__main__':
    unittest.main()
