# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.config_entry import ConfigEntry

class TestConfigEntry(unittest.TestCase):
    """ConfigEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ConfigEntry:
        """Test ConfigEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ConfigEntry`
        """
        model = ConfigEntry()
        if include_optional:
            return ConfigEntry(
                key = 'app/version',
                value = {minSupported=1.0.0, latest=1.0.0}
            )
        else:
            return ConfigEntry(
        )
        """

    def testConfigEntry(self):
        """Test ConfigEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
