# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.api.themes_api import ThemesApi


class TestThemesApi(unittest.TestCase):
    """ThemesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ThemesApi()

    def tearDown(self) -> None:
        pass

    def test_activate_theme(self) -> None:
        """Test case for activate_theme

        Activate a theme
        """
        pass

    def test_create_theme(self) -> None:
        """Test case for create_theme

        Create a new theme
        """
        pass

    def test_delete_theme(self) -> None:
        """Test case for delete_theme

        Delete a theme
        """
        pass

    def test_get_theme_by_id(self) -> None:
        """Test case for get_theme_by_id

        Get theme by ID
        """
        pass

    def test_get_themes(self) -> None:
        """Test case for get_themes

        List themes for merchant
        """
        pass

    def test_update_theme(self) -> None:
        """Test case for update_theme

        Update a theme
        """
        pass


if __name__ == '__main__':
    unittest.main()
