# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.api.pricing_api import PricingApi


class TestPricingApi(unittest.TestCase):
    """PricingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PricingApi()

    def tearDown(self) -> None:
        pass

    def test_get_public_pricing(self) -> None:
        """Test case for get_public_pricing

        Get public pricing tiers
        """
        pass


if __name__ == '__main__':
    unittest.main()
