# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.set_custom_rate_limits200_response import SetCustomRateLimits200Response

class TestSetCustomRateLimits200Response(unittest.TestCase):
    """SetCustomRateLimits200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetCustomRateLimits200Response:
        """Test SetCustomRateLimits200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetCustomRateLimits200Response`
        """
        model = SetCustomRateLimits200Response()
        if include_optional:
            return SetCustomRateLimits200Response(
                success = True,
                data = subtrackr_sdk.models.set_custom_rate_limits_200_response_data.setCustomRateLimits_200_response_data(
                    api_key = 'sk_live_abc123', 
                    limits = subtrackr_sdk.models.get_rate_limit_status_200_response_data_limits.getRateLimitStatus_200_response_data_limits(
                        hourly_limit = 56, 
                        daily_limit = 56, 
                        monthly_limit = 56, 
                        burst_limit = 56, 
                        concurrent_limit = 56, ), ),
                request_id = 'req_abc123'
            )
        else:
            return SetCustomRateLimits200Response(
        )
        """

    def testSetCustomRateLimits200Response(self):
        """Test SetCustomRateLimits200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
