# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.api.cache_api import CacheApi


class TestCacheApi(unittest.TestCase):
    """CacheApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CacheApi()

    def tearDown(self) -> None:
        pass

    def test_purge_user_cache(self) -> None:
        """Test case for purge_user_cache

        Purge user-scoped cache entries
        """
        pass


if __name__ == '__main__':
    unittest.main()
