# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_public_pricing200_response import GetPublicPricing200Response

class TestGetPublicPricing200Response(unittest.TestCase):
    """GetPublicPricing200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPublicPricing200Response:
        """Test GetPublicPricing200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPublicPricing200Response`
        """
        model = GetPublicPricing200Response()
        if include_optional:
            return GetPublicPricing200Response(
                success = True,
                data = [
                    subtrackr_sdk.models.pricing_tier.PricingTier(
                        plan_id = 'premium', 
                        monthly_price = 29.99, 
                        yearly_price = 299.99, 
                        currency = 'USD', 
                        discount_percent = 17, )
                    ],
                request_id = 'req_abc123'
            )
        else:
            return GetPublicPricing200Response(
        )
        """

    def testGetPublicPricing200Response(self):
        """Test GetPublicPricing200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
