# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.graphql_query200_response import GraphqlQuery200Response

class TestGraphqlQuery200Response(unittest.TestCase):
    """GraphqlQuery200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphqlQuery200Response:
        """Test GraphqlQuery200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphqlQuery200Response`
        """
        model = GraphqlQuery200Response()
        if include_optional:
            return GraphqlQuery200Response(
                data = None,
                errors = [
                    subtrackr_sdk.models.graphql_query_200_response_errors_inner.graphqlQuery_200_response_errors_inner(
                        message = '', )
                    ]
            )
        else:
            return GraphqlQuery200Response(
        )
        """

    def testGraphqlQuery200Response(self):
        """Test GraphqlQuery200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
