# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.delete_theme200_response import DeleteTheme200Response

class TestDeleteTheme200Response(unittest.TestCase):
    """DeleteTheme200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteTheme200Response:
        """Test DeleteTheme200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteTheme200Response`
        """
        model = DeleteTheme200Response()
        if include_optional:
            return DeleteTheme200Response(
                success = True,
                data = subtrackr_sdk.models.delete_theme_200_response_data.deleteTheme_200_response_data(
                    deleted = True, ),
                request_id = 'req_abc123'
            )
        else:
            return DeleteTheme200Response(
        )
        """

    def testDeleteTheme200Response(self):
        """Test DeleteTheme200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
