# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_status200_response_data_current import GetRateLimitStatus200ResponseDataCurrent

class TestGetRateLimitStatus200ResponseDataCurrent(unittest.TestCase):
    """GetRateLimitStatus200ResponseDataCurrent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitStatus200ResponseDataCurrent:
        """Test GetRateLimitStatus200ResponseDataCurrent
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitStatus200ResponseDataCurrent`
        """
        model = GetRateLimitStatus200ResponseDataCurrent()
        if include_optional:
            return GetRateLimitStatus200ResponseDataCurrent(
                hourly = 56,
                daily = 56,
                monthly = 56,
                burst_tokens = 56
            )
        else:
            return GetRateLimitStatus200ResponseDataCurrent(
        )
        """

    def testGetRateLimitStatus200ResponseDataCurrent(self):
        """Test GetRateLimitStatus200ResponseDataCurrent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
