# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.theme_input import ThemeInput

class TestThemeInput(unittest.TestCase):
    """ThemeInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ThemeInput:
        """Test ThemeInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ThemeInput`
        """
        model = ThemeInput()
        if include_optional:
            return ThemeInput(
                id = 'theme_dark',
                name = 'Dark Theme',
                config = {primaryColor=#1a1a2e, secondaryColor=#16213e, fontFamily=Inter}
            )
        else:
            return ThemeInput(
                id = 'theme_dark',
                name = 'Dark Theme',
                config = {primaryColor=#1a1a2e, secondaryColor=#16213e, fontFamily=Inter},
        )
        """

    def testThemeInput(self):
        """Test ThemeInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
