# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.manage_bypass200_response_data import ManageBypass200ResponseData

class TestManageBypass200ResponseData(unittest.TestCase):
    """ManageBypass200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ManageBypass200ResponseData:
        """Test ManageBypass200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ManageBypass200ResponseData`
        """
        model = ManageBypass200ResponseData()
        if include_optional:
            return ManageBypass200ResponseData(
                bypass_keys = [sk_live_abc123, sk_live_xyz789],
                bypass_users = [user_123]
            )
        else:
            return ManageBypass200ResponseData(
        )
        """

    def testManageBypass200ResponseData(self):
        """Test ManageBypass200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
