# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.set_custom_rate_limits_request_limits import SetCustomRateLimitsRequestLimits

class TestSetCustomRateLimitsRequestLimits(unittest.TestCase):
    """SetCustomRateLimitsRequestLimits unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetCustomRateLimitsRequestLimits:
        """Test SetCustomRateLimitsRequestLimits
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetCustomRateLimitsRequestLimits`
        """
        model = SetCustomRateLimitsRequestLimits()
        if include_optional:
            return SetCustomRateLimitsRequestLimits(
                hourly_limit = 5000,
                daily_limit = 50000,
                monthly_limit = 500000,
                burst_limit = 200,
                concurrent_limit = 50
            )
        else:
            return SetCustomRateLimitsRequestLimits(
        )
        """

    def testSetCustomRateLimitsRequestLimits(self):
        """Test SetCustomRateLimitsRequestLimits"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
