# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_analytics200_response_data_by_tier_free import GetRateLimitAnalytics200ResponseDataByTierFREE

class TestGetRateLimitAnalytics200ResponseDataByTierFREE(unittest.TestCase):
    """GetRateLimitAnalytics200ResponseDataByTierFREE unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitAnalytics200ResponseDataByTierFREE:
        """Test GetRateLimitAnalytics200ResponseDataByTierFREE
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitAnalytics200ResponseDataByTierFREE`
        """
        model = GetRateLimitAnalytics200ResponseDataByTierFREE()
        if include_optional:
            return GetRateLimitAnalytics200ResponseDataByTierFREE(
                requests = 56,
                hits = 56,
                hit_rate = 1.337
            )
        else:
            return GetRateLimitAnalytics200ResponseDataByTierFREE(
        )
        """

    def testGetRateLimitAnalytics200ResponseDataByTierFREE(self):
        """Test GetRateLimitAnalytics200ResponseDataByTierFREE"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
