# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_analytics200_response_data import GetRateLimitAnalytics200ResponseData

class TestGetRateLimitAnalytics200ResponseData(unittest.TestCase):
    """GetRateLimitAnalytics200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitAnalytics200ResponseData:
        """Test GetRateLimitAnalytics200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitAnalytics200ResponseData`
        """
        model = GetRateLimitAnalytics200ResponseData()
        if include_optional:
            return GetRateLimitAnalytics200ResponseData(
                total_requests = 12345,
                rate_limit_hits = 123,
                hit_rate = 0.01,
                top_throttled_keys = [
                    subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_top_throttled_keys_inner.getRateLimitAnalytics_200_response_data_topThrottledKeys_inner(
                        key = '', 
                        hits = 56, )
                    ],
                top_throttled_endpoints = [
                    subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_top_throttled_endpoints_inner.getRateLimitAnalytics_200_response_data_topThrottledEndpoints_inner(
                        endpoint = '', 
                        hits = 56, )
                    ],
                by_tier = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier.getRateLimitAnalytics_200_response_data_byTier(
                    free = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                        requests = 56, 
                        hits = 56, 
                        hit_rate = 1.337, ), 
                    basic = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                        requests = 56, 
                        hits = 56, 
                        hit_rate = 1.337, ), 
                    premium = , 
                    enterprise = , )
            )
        else:
            return GetRateLimitAnalytics200ResponseData(
        )
        """

    def testGetRateLimitAnalytics200ResponseData(self):
        """Test GetRateLimitAnalytics200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
