# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_status200_response import GetRateLimitStatus200Response

class TestGetRateLimitStatus200Response(unittest.TestCase):
    """GetRateLimitStatus200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitStatus200Response:
        """Test GetRateLimitStatus200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitStatus200Response`
        """
        model = GetRateLimitStatus200Response()
        if include_optional:
            return GetRateLimitStatus200Response(
                success = True,
                data = subtrackr_sdk.models.get_rate_limit_status_200_response_data.getRateLimitStatus_200_response_data(
                    limits = subtrackr_sdk.models.get_rate_limit_status_200_response_data_limits.getRateLimitStatus_200_response_data_limits(
                        hourly_limit = 56, 
                        daily_limit = 56, 
                        monthly_limit = 56, 
                        burst_limit = 56, 
                        concurrent_limit = 56, ), 
                    current = subtrackr_sdk.models.get_rate_limit_status_200_response_data_current.getRateLimitStatus_200_response_data_current(
                        hourly = 56, 
                        daily = 56, 
                        monthly = 56, 
                        burst_tokens = 56, ), 
                    remaining = subtrackr_sdk.models.get_rate_limit_status_200_response_data_current.getRateLimitStatus_200_response_data_current(
                        hourly = 56, 
                        daily = 56, 
                        monthly = 56, 
                        burst_tokens = 56, ), 
                    reset_at = subtrackr_sdk.models.get_rate_limit_status_200_response_data_reset_at.getRateLimitStatus_200_response_data_resetAt(
                        hourly = 56, 
                        daily = 56, 
                        monthly = 56, ), ),
                request_id = 'req_abc123'
            )
        else:
            return GetRateLimitStatus200Response(
        )
        """

    def testGetRateLimitStatus200Response(self):
        """Test GetRateLimitStatus200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
