# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_analytics200_response_data_by_tier import GetRateLimitAnalytics200ResponseDataByTier

class TestGetRateLimitAnalytics200ResponseDataByTier(unittest.TestCase):
    """GetRateLimitAnalytics200ResponseDataByTier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitAnalytics200ResponseDataByTier:
        """Test GetRateLimitAnalytics200ResponseDataByTier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitAnalytics200ResponseDataByTier`
        """
        model = GetRateLimitAnalytics200ResponseDataByTier()
        if include_optional:
            return GetRateLimitAnalytics200ResponseDataByTier(
                free = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                    requests = 56, 
                    hits = 56, 
                    hit_rate = 1.337, ),
                basic = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                    requests = 56, 
                    hits = 56, 
                    hit_rate = 1.337, ),
                premium = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                    requests = 56, 
                    hits = 56, 
                    hit_rate = 1.337, ),
                enterprise = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                    requests = 56, 
                    hits = 56, 
                    hit_rate = 1.337, )
            )
        else:
            return GetRateLimitAnalytics200ResponseDataByTier(
        )
        """

    def testGetRateLimitAnalytics200ResponseDataByTier(self):
        """Test GetRateLimitAnalytics200ResponseDataByTier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
