# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_status200_response_data_reset_at import GetRateLimitStatus200ResponseDataResetAt

class TestGetRateLimitStatus200ResponseDataResetAt(unittest.TestCase):
    """GetRateLimitStatus200ResponseDataResetAt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitStatus200ResponseDataResetAt:
        """Test GetRateLimitStatus200ResponseDataResetAt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitStatus200ResponseDataResetAt`
        """
        model = GetRateLimitStatus200ResponseDataResetAt()
        if include_optional:
            return GetRateLimitStatus200ResponseDataResetAt(
                hourly = 56,
                daily = 56,
                monthly = 56
            )
        else:
            return GetRateLimitStatus200ResponseDataResetAt(
        )
        """

    def testGetRateLimitStatus200ResponseDataResetAt(self):
        """Test GetRateLimitStatus200ResponseDataResetAt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
