# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_rate_limit_analytics200_response import GetRateLimitAnalytics200Response

class TestGetRateLimitAnalytics200Response(unittest.TestCase):
    """GetRateLimitAnalytics200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetRateLimitAnalytics200Response:
        """Test GetRateLimitAnalytics200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetRateLimitAnalytics200Response`
        """
        model = GetRateLimitAnalytics200Response()
        if include_optional:
            return GetRateLimitAnalytics200Response(
                success = True,
                data = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data.getRateLimitAnalytics_200_response_data(
                    total_requests = 12345, 
                    rate_limit_hits = 123, 
                    hit_rate = 0.01, 
                    top_throttled_keys = [
                        subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_top_throttled_keys_inner.getRateLimitAnalytics_200_response_data_topThrottledKeys_inner(
                            key = '', 
                            hits = 56, )
                        ], 
                    top_throttled_endpoints = [
                        subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_top_throttled_endpoints_inner.getRateLimitAnalytics_200_response_data_topThrottledEndpoints_inner(
                            endpoint = '', 
                            hits = 56, )
                        ], 
                    by_tier = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier.getRateLimitAnalytics_200_response_data_byTier(
                        free = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                            requests = 56, 
                            hits = 56, 
                            hit_rate = 1.337, ), 
                        basic = subtrackr_sdk.models.get_rate_limit_analytics_200_response_data_by_tier_free.getRateLimitAnalytics_200_response_data_byTier_FREE(
                            requests = 56, 
                            hits = 56, 
                            hit_rate = 1.337, ), 
                        premium = , 
                        enterprise = , ), ),
                request_id = 'req_abc123'
            )
        else:
            return GetRateLimitAnalytics200Response(
        )
        """

    def testGetRateLimitAnalytics200Response(self):
        """Test GetRateLimitAnalytics200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
