# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.set_custom_rate_limits_request import SetCustomRateLimitsRequest

class TestSetCustomRateLimitsRequest(unittest.TestCase):
    """SetCustomRateLimitsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetCustomRateLimitsRequest:
        """Test SetCustomRateLimitsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetCustomRateLimitsRequest`
        """
        model = SetCustomRateLimitsRequest()
        if include_optional:
            return SetCustomRateLimitsRequest(
                api_key = 'sk_live_abc123',
                limits = subtrackr_sdk.models.set_custom_rate_limits_request_limits.setCustomRateLimits_request_limits(
                    hourly_limit = 5000, 
                    daily_limit = 50000, 
                    monthly_limit = 500000, 
                    burst_limit = 200, 
                    concurrent_limit = 50, )
            )
        else:
            return SetCustomRateLimitsRequest(
                api_key = 'sk_live_abc123',
        )
        """

    def testSetCustomRateLimitsRequest(self):
        """Test SetCustomRateLimitsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
