# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.get_public_config200_response_data import GetPublicConfig200ResponseData

class TestGetPublicConfig200ResponseData(unittest.TestCase):
    """GetPublicConfig200ResponseData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPublicConfig200ResponseData:
        """Test GetPublicConfig200ResponseData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPublicConfig200ResponseData`
        """
        model = GetPublicConfig200ResponseData()
        if include_optional:
            return GetPublicConfig200ResponseData(
                key = 'app/version',
                value = {minSupported=1.0.0, latest=1.0.0}
            )
        else:
            return GetPublicConfig200ResponseData(
        )
        """

    def testGetPublicConfig200ResponseData(self):
        """Test GetPublicConfig200ResponseData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
