# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.plan_update_input import PlanUpdateInput

class TestPlanUpdateInput(unittest.TestCase):
    """PlanUpdateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PlanUpdateInput:
        """Test PlanUpdateInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PlanUpdateInput`
        """
        model = PlanUpdateInput()
        if include_optional:
            return PlanUpdateInput(
                name = 'Premium Plan Pro',
                price = 49.99,
                currency = 'USD',
                billing_cycle = 'yearly',
                features = [Unlimited subscriptions, Advanced analytics, Priority support],
                is_active = True
            )
        else:
            return PlanUpdateInput(
        )
        """

    def testPlanUpdateInput(self):
        """Test PlanUpdateInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
