# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.pricing_update_input import PricingUpdateInput

class TestPricingUpdateInput(unittest.TestCase):
    """PricingUpdateInput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricingUpdateInput:
        """Test PricingUpdateInput
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricingUpdateInput`
        """
        model = PricingUpdateInput()
        if include_optional:
            return PricingUpdateInput(
                monthly_price = 39.99,
                yearly_price = 399.99,
                discount_percent = 20
            )
        else:
            return PricingUpdateInput(
        )
        """

    def testPricingUpdateInput(self):
        """Test PricingUpdateInput"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
