# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from subtrackr_sdk.models.graphql_query_request import GraphqlQueryRequest

class TestGraphqlQueryRequest(unittest.TestCase):
    """GraphqlQueryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GraphqlQueryRequest:
        """Test GraphqlQueryRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GraphqlQueryRequest`
        """
        model = GraphqlQueryRequest()
        if include_optional:
            return GraphqlQueryRequest(
                query = 'query {
  plans {
    id
    name
    price
  }
}
',
                variables = {}
            )
        else:
            return GraphqlQueryRequest(
        )
        """

    def testGraphqlQueryRequest(self):
        """Test GraphqlQueryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
