/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ListPlans200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListPlans200Response{}

// ListPlans200Response struct for ListPlans200Response
type ListPlans200Response struct {
	Success *bool `json:"success,omitempty"`
	Data []Plan `json:"data,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewListPlans200Response instantiates a new ListPlans200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListPlans200Response() *ListPlans200Response {
	this := ListPlans200Response{}
	return &this
}

// NewListPlans200ResponseWithDefaults instantiates a new ListPlans200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListPlans200ResponseWithDefaults() *ListPlans200Response {
	this := ListPlans200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ListPlans200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlans200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ListPlans200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ListPlans200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListPlans200Response) GetData() []Plan {
	if o == nil || IsNil(o.Data) {
		var ret []Plan
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlans200Response) GetDataOk() ([]Plan, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListPlans200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Plan and assigns it to the Data field.
func (o *ListPlans200Response) SetData(v []Plan) {
	o.Data = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ListPlans200Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListPlans200Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ListPlans200Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ListPlans200Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o ListPlans200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListPlans200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableListPlans200Response struct {
	value *ListPlans200Response
	isSet bool
}

func (v NullableListPlans200Response) Get() *ListPlans200Response {
	return v.value
}

func (v *NullableListPlans200Response) Set(val *ListPlans200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListPlans200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListPlans200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListPlans200Response(val *ListPlans200Response) *NullableListPlans200Response {
	return &NullableListPlans200Response{value: val, isSet: true}
}

func (v NullableListPlans200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListPlans200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


