/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitStatus200ResponseDataCurrent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitStatus200ResponseDataCurrent{}

// GetRateLimitStatus200ResponseDataCurrent struct for GetRateLimitStatus200ResponseDataCurrent
type GetRateLimitStatus200ResponseDataCurrent struct {
	Hourly *int32 `json:"hourly,omitempty"`
	Daily *int32 `json:"daily,omitempty"`
	Monthly *int32 `json:"monthly,omitempty"`
	BurstTokens *int32 `json:"burstTokens,omitempty"`
}

// NewGetRateLimitStatus200ResponseDataCurrent instantiates a new GetRateLimitStatus200ResponseDataCurrent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitStatus200ResponseDataCurrent() *GetRateLimitStatus200ResponseDataCurrent {
	this := GetRateLimitStatus200ResponseDataCurrent{}
	return &this
}

// NewGetRateLimitStatus200ResponseDataCurrentWithDefaults instantiates a new GetRateLimitStatus200ResponseDataCurrent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitStatus200ResponseDataCurrentWithDefaults() *GetRateLimitStatus200ResponseDataCurrent {
	this := GetRateLimitStatus200ResponseDataCurrent{}
	return &this
}

// GetHourly returns the Hourly field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetHourly() int32 {
	if o == nil || IsNil(o.Hourly) {
		var ret int32
		return ret
	}
	return *o.Hourly
}

// GetHourlyOk returns a tuple with the Hourly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetHourlyOk() (*int32, bool) {
	if o == nil || IsNil(o.Hourly) {
		return nil, false
	}
	return o.Hourly, true
}

// HasHourly returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) HasHourly() bool {
	if o != nil && !IsNil(o.Hourly) {
		return true
	}

	return false
}

// SetHourly gets a reference to the given int32 and assigns it to the Hourly field.
func (o *GetRateLimitStatus200ResponseDataCurrent) SetHourly(v int32) {
	o.Hourly = &v
}

// GetDaily returns the Daily field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetDaily() int32 {
	if o == nil || IsNil(o.Daily) {
		var ret int32
		return ret
	}
	return *o.Daily
}

// GetDailyOk returns a tuple with the Daily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetDailyOk() (*int32, bool) {
	if o == nil || IsNil(o.Daily) {
		return nil, false
	}
	return o.Daily, true
}

// HasDaily returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) HasDaily() bool {
	if o != nil && !IsNil(o.Daily) {
		return true
	}

	return false
}

// SetDaily gets a reference to the given int32 and assigns it to the Daily field.
func (o *GetRateLimitStatus200ResponseDataCurrent) SetDaily(v int32) {
	o.Daily = &v
}

// GetMonthly returns the Monthly field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetMonthly() int32 {
	if o == nil || IsNil(o.Monthly) {
		var ret int32
		return ret
	}
	return *o.Monthly
}

// GetMonthlyOk returns a tuple with the Monthly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetMonthlyOk() (*int32, bool) {
	if o == nil || IsNil(o.Monthly) {
		return nil, false
	}
	return o.Monthly, true
}

// HasMonthly returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) HasMonthly() bool {
	if o != nil && !IsNil(o.Monthly) {
		return true
	}

	return false
}

// SetMonthly gets a reference to the given int32 and assigns it to the Monthly field.
func (o *GetRateLimitStatus200ResponseDataCurrent) SetMonthly(v int32) {
	o.Monthly = &v
}

// GetBurstTokens returns the BurstTokens field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetBurstTokens() int32 {
	if o == nil || IsNil(o.BurstTokens) {
		var ret int32
		return ret
	}
	return *o.BurstTokens
}

// GetBurstTokensOk returns a tuple with the BurstTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) GetBurstTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstTokens) {
		return nil, false
	}
	return o.BurstTokens, true
}

// HasBurstTokens returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseDataCurrent) HasBurstTokens() bool {
	if o != nil && !IsNil(o.BurstTokens) {
		return true
	}

	return false
}

// SetBurstTokens gets a reference to the given int32 and assigns it to the BurstTokens field.
func (o *GetRateLimitStatus200ResponseDataCurrent) SetBurstTokens(v int32) {
	o.BurstTokens = &v
}

func (o GetRateLimitStatus200ResponseDataCurrent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitStatus200ResponseDataCurrent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hourly) {
		toSerialize["hourly"] = o.Hourly
	}
	if !IsNil(o.Daily) {
		toSerialize["daily"] = o.Daily
	}
	if !IsNil(o.Monthly) {
		toSerialize["monthly"] = o.Monthly
	}
	if !IsNil(o.BurstTokens) {
		toSerialize["burstTokens"] = o.BurstTokens
	}
	return toSerialize, nil
}

type NullableGetRateLimitStatus200ResponseDataCurrent struct {
	value *GetRateLimitStatus200ResponseDataCurrent
	isSet bool
}

func (v NullableGetRateLimitStatus200ResponseDataCurrent) Get() *GetRateLimitStatus200ResponseDataCurrent {
	return v.value
}

func (v *NullableGetRateLimitStatus200ResponseDataCurrent) Set(val *GetRateLimitStatus200ResponseDataCurrent) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitStatus200ResponseDataCurrent) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitStatus200ResponseDataCurrent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitStatus200ResponseDataCurrent(val *GetRateLimitStatus200ResponseDataCurrent) *NullableGetRateLimitStatus200ResponseDataCurrent {
	return &NullableGetRateLimitStatus200ResponseDataCurrent{value: val, isSet: true}
}

func (v NullableGetRateLimitStatus200ResponseDataCurrent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitStatus200ResponseDataCurrent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


