/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ThemeUpdateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThemeUpdateInput{}

// ThemeUpdateInput struct for ThemeUpdateInput
type ThemeUpdateInput struct {
	Name *string `json:"name,omitempty"`
	Config map[string]interface{} `json:"config,omitempty"`
	IsActive *bool `json:"isActive,omitempty"`
}

// NewThemeUpdateInput instantiates a new ThemeUpdateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThemeUpdateInput() *ThemeUpdateInput {
	this := ThemeUpdateInput{}
	return &this
}

// NewThemeUpdateInputWithDefaults instantiates a new ThemeUpdateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThemeUpdateInputWithDefaults() *ThemeUpdateInput {
	this := ThemeUpdateInput{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ThemeUpdateInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThemeUpdateInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ThemeUpdateInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ThemeUpdateInput) SetName(v string) {
	o.Name = &v
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *ThemeUpdateInput) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThemeUpdateInput) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *ThemeUpdateInput) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *ThemeUpdateInput) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *ThemeUpdateInput) GetIsActive() bool {
	if o == nil || IsNil(o.IsActive) {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ThemeUpdateInput) GetIsActiveOk() (*bool, bool) {
	if o == nil || IsNil(o.IsActive) {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *ThemeUpdateInput) HasIsActive() bool {
	if o != nil && !IsNil(o.IsActive) {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *ThemeUpdateInput) SetIsActive(v bool) {
	o.IsActive = &v
}

func (o ThemeUpdateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThemeUpdateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.IsActive) {
		toSerialize["isActive"] = o.IsActive
	}
	return toSerialize, nil
}

type NullableThemeUpdateInput struct {
	value *ThemeUpdateInput
	isSet bool
}

func (v NullableThemeUpdateInput) Get() *ThemeUpdateInput {
	return v.value
}

func (v *NullableThemeUpdateInput) Set(val *ThemeUpdateInput) {
	v.value = val
	v.isSet = true
}

func (v NullableThemeUpdateInput) IsSet() bool {
	return v.isSet
}

func (v *NullableThemeUpdateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThemeUpdateInput(val *ThemeUpdateInput) *NullableThemeUpdateInput {
	return &NullableThemeUpdateInput{value: val, isSet: true}
}

func (v NullableThemeUpdateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThemeUpdateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


