/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PricingUpdateInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PricingUpdateInput{}

// PricingUpdateInput struct for PricingUpdateInput
type PricingUpdateInput struct {
	MonthlyPrice *float32 `json:"monthlyPrice,omitempty"`
	YearlyPrice *float32 `json:"yearlyPrice,omitempty"`
	DiscountPercent *float32 `json:"discountPercent,omitempty"`
}

// NewPricingUpdateInput instantiates a new PricingUpdateInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPricingUpdateInput() *PricingUpdateInput {
	this := PricingUpdateInput{}
	return &this
}

// NewPricingUpdateInputWithDefaults instantiates a new PricingUpdateInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPricingUpdateInputWithDefaults() *PricingUpdateInput {
	this := PricingUpdateInput{}
	return &this
}

// GetMonthlyPrice returns the MonthlyPrice field value if set, zero value otherwise.
func (o *PricingUpdateInput) GetMonthlyPrice() float32 {
	if o == nil || IsNil(o.MonthlyPrice) {
		var ret float32
		return ret
	}
	return *o.MonthlyPrice
}

// GetMonthlyPriceOk returns a tuple with the MonthlyPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingUpdateInput) GetMonthlyPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.MonthlyPrice) {
		return nil, false
	}
	return o.MonthlyPrice, true
}

// HasMonthlyPrice returns a boolean if a field has been set.
func (o *PricingUpdateInput) HasMonthlyPrice() bool {
	if o != nil && !IsNil(o.MonthlyPrice) {
		return true
	}

	return false
}

// SetMonthlyPrice gets a reference to the given float32 and assigns it to the MonthlyPrice field.
func (o *PricingUpdateInput) SetMonthlyPrice(v float32) {
	o.MonthlyPrice = &v
}

// GetYearlyPrice returns the YearlyPrice field value if set, zero value otherwise.
func (o *PricingUpdateInput) GetYearlyPrice() float32 {
	if o == nil || IsNil(o.YearlyPrice) {
		var ret float32
		return ret
	}
	return *o.YearlyPrice
}

// GetYearlyPriceOk returns a tuple with the YearlyPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingUpdateInput) GetYearlyPriceOk() (*float32, bool) {
	if o == nil || IsNil(o.YearlyPrice) {
		return nil, false
	}
	return o.YearlyPrice, true
}

// HasYearlyPrice returns a boolean if a field has been set.
func (o *PricingUpdateInput) HasYearlyPrice() bool {
	if o != nil && !IsNil(o.YearlyPrice) {
		return true
	}

	return false
}

// SetYearlyPrice gets a reference to the given float32 and assigns it to the YearlyPrice field.
func (o *PricingUpdateInput) SetYearlyPrice(v float32) {
	o.YearlyPrice = &v
}

// GetDiscountPercent returns the DiscountPercent field value if set, zero value otherwise.
func (o *PricingUpdateInput) GetDiscountPercent() float32 {
	if o == nil || IsNil(o.DiscountPercent) {
		var ret float32
		return ret
	}
	return *o.DiscountPercent
}

// GetDiscountPercentOk returns a tuple with the DiscountPercent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PricingUpdateInput) GetDiscountPercentOk() (*float32, bool) {
	if o == nil || IsNil(o.DiscountPercent) {
		return nil, false
	}
	return o.DiscountPercent, true
}

// HasDiscountPercent returns a boolean if a field has been set.
func (o *PricingUpdateInput) HasDiscountPercent() bool {
	if o != nil && !IsNil(o.DiscountPercent) {
		return true
	}

	return false
}

// SetDiscountPercent gets a reference to the given float32 and assigns it to the DiscountPercent field.
func (o *PricingUpdateInput) SetDiscountPercent(v float32) {
	o.DiscountPercent = &v
}

func (o PricingUpdateInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PricingUpdateInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MonthlyPrice) {
		toSerialize["monthlyPrice"] = o.MonthlyPrice
	}
	if !IsNil(o.YearlyPrice) {
		toSerialize["yearlyPrice"] = o.YearlyPrice
	}
	if !IsNil(o.DiscountPercent) {
		toSerialize["discountPercent"] = o.DiscountPercent
	}
	return toSerialize, nil
}

type NullablePricingUpdateInput struct {
	value *PricingUpdateInput
	isSet bool
}

func (v NullablePricingUpdateInput) Get() *PricingUpdateInput {
	return v.value
}

func (v *NullablePricingUpdateInput) Set(val *PricingUpdateInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePricingUpdateInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePricingUpdateInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePricingUpdateInput(val *PricingUpdateInput) *NullablePricingUpdateInput {
	return &NullablePricingUpdateInput{value: val, isSet: true}
}

func (v NullablePricingUpdateInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePricingUpdateInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


