/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner{}

// GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner struct for GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner
type GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner struct {
	Endpoint *string `json:"endpoint,omitempty"`
	Hits *int32 `json:"hits,omitempty"`
}

// NewGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner instantiates a new GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner() *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner {
	this := GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner{}
	return &this
}

// NewGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInnerWithDefaults instantiates a new GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInnerWithDefaults() *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner {
	this := GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner{}
	return &this
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) GetHits() int32 {
	if o == nil || IsNil(o.Hits) {
		var ret int32
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) GetHitsOk() (*int32, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given int32 and assigns it to the Hits field.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) SetHits(v int32) {
	o.Hits = &v
}

func (o GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	return toSerialize, nil
}

type NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner struct {
	value *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner
	isSet bool
}

func (v NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) Get() *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner {
	return v.value
}

func (v *NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) Set(val *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner(val *GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) *NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner {
	return &NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner{value: val, isSet: true}
}

func (v NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


