/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ThemeInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ThemeInput{}

// ThemeInput struct for ThemeInput
type ThemeInput struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Config map[string]interface{} `json:"config"`
}

type _ThemeInput ThemeInput

// NewThemeInput instantiates a new ThemeInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewThemeInput(id string, name string, config map[string]interface{}) *ThemeInput {
	this := ThemeInput{}
	this.Id = id
	this.Name = name
	this.Config = config
	return &this
}

// NewThemeInputWithDefaults instantiates a new ThemeInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewThemeInputWithDefaults() *ThemeInput {
	this := ThemeInput{}
	return &this
}

// GetId returns the Id field value
func (o *ThemeInput) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ThemeInput) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ThemeInput) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *ThemeInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ThemeInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ThemeInput) SetName(v string) {
	o.Name = v
}

// GetConfig returns the Config field value
func (o *ThemeInput) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *ThemeInput) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *ThemeInput) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o ThemeInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ThemeInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["config"] = o.Config
	return toSerialize, nil
}

func (o *ThemeInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"config",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varThemeInput := _ThemeInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varThemeInput)

	if err != nil {
		return err
	}

	*o = ThemeInput(varThemeInput)

	return err
}

type NullableThemeInput struct {
	value *ThemeInput
	isSet bool
}

func (v NullableThemeInput) Get() *ThemeInput {
	return v.value
}

func (v *NullableThemeInput) Set(val *ThemeInput) {
	v.value = val
	v.isSet = true
}

func (v NullableThemeInput) IsSet() bool {
	return v.isSet
}

func (v *NullableThemeInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableThemeInput(val *ThemeInput) *NullableThemeInput {
	return &NullableThemeInput{value: val, isSet: true}
}

func (v NullableThemeInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableThemeInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


