/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitAnalytics200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitAnalytics200ResponseData{}

// GetRateLimitAnalytics200ResponseData struct for GetRateLimitAnalytics200ResponseData
type GetRateLimitAnalytics200ResponseData struct {
	TotalRequests *int32 `json:"totalRequests,omitempty"`
	RateLimitHits *int32 `json:"rateLimitHits,omitempty"`
	HitRate *float32 `json:"hitRate,omitempty"`
	TopThrottledKeys []GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner `json:"topThrottledKeys,omitempty"`
	TopThrottledEndpoints []GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner `json:"topThrottledEndpoints,omitempty"`
	ByTier *GetRateLimitAnalytics200ResponseDataByTier `json:"byTier,omitempty"`
}

// NewGetRateLimitAnalytics200ResponseData instantiates a new GetRateLimitAnalytics200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitAnalytics200ResponseData() *GetRateLimitAnalytics200ResponseData {
	this := GetRateLimitAnalytics200ResponseData{}
	return &this
}

// NewGetRateLimitAnalytics200ResponseDataWithDefaults instantiates a new GetRateLimitAnalytics200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitAnalytics200ResponseDataWithDefaults() *GetRateLimitAnalytics200ResponseData {
	this := GetRateLimitAnalytics200ResponseData{}
	return &this
}

// GetTotalRequests returns the TotalRequests field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseData) GetTotalRequests() int32 {
	if o == nil || IsNil(o.TotalRequests) {
		var ret int32
		return ret
	}
	return *o.TotalRequests
}

// GetTotalRequestsOk returns a tuple with the TotalRequests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseData) GetTotalRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalRequests) {
		return nil, false
	}
	return o.TotalRequests, true
}

// HasTotalRequests returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseData) HasTotalRequests() bool {
	if o != nil && !IsNil(o.TotalRequests) {
		return true
	}

	return false
}

// SetTotalRequests gets a reference to the given int32 and assigns it to the TotalRequests field.
func (o *GetRateLimitAnalytics200ResponseData) SetTotalRequests(v int32) {
	o.TotalRequests = &v
}

// GetRateLimitHits returns the RateLimitHits field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseData) GetRateLimitHits() int32 {
	if o == nil || IsNil(o.RateLimitHits) {
		var ret int32
		return ret
	}
	return *o.RateLimitHits
}

// GetRateLimitHitsOk returns a tuple with the RateLimitHits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseData) GetRateLimitHitsOk() (*int32, bool) {
	if o == nil || IsNil(o.RateLimitHits) {
		return nil, false
	}
	return o.RateLimitHits, true
}

// HasRateLimitHits returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseData) HasRateLimitHits() bool {
	if o != nil && !IsNil(o.RateLimitHits) {
		return true
	}

	return false
}

// SetRateLimitHits gets a reference to the given int32 and assigns it to the RateLimitHits field.
func (o *GetRateLimitAnalytics200ResponseData) SetRateLimitHits(v int32) {
	o.RateLimitHits = &v
}

// GetHitRate returns the HitRate field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseData) GetHitRate() float32 {
	if o == nil || IsNil(o.HitRate) {
		var ret float32
		return ret
	}
	return *o.HitRate
}

// GetHitRateOk returns a tuple with the HitRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseData) GetHitRateOk() (*float32, bool) {
	if o == nil || IsNil(o.HitRate) {
		return nil, false
	}
	return o.HitRate, true
}

// HasHitRate returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseData) HasHitRate() bool {
	if o != nil && !IsNil(o.HitRate) {
		return true
	}

	return false
}

// SetHitRate gets a reference to the given float32 and assigns it to the HitRate field.
func (o *GetRateLimitAnalytics200ResponseData) SetHitRate(v float32) {
	o.HitRate = &v
}

// GetTopThrottledKeys returns the TopThrottledKeys field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseData) GetTopThrottledKeys() []GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner {
	if o == nil || IsNil(o.TopThrottledKeys) {
		var ret []GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner
		return ret
	}
	return o.TopThrottledKeys
}

// GetTopThrottledKeysOk returns a tuple with the TopThrottledKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseData) GetTopThrottledKeysOk() ([]GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner, bool) {
	if o == nil || IsNil(o.TopThrottledKeys) {
		return nil, false
	}
	return o.TopThrottledKeys, true
}

// HasTopThrottledKeys returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseData) HasTopThrottledKeys() bool {
	if o != nil && !IsNil(o.TopThrottledKeys) {
		return true
	}

	return false
}

// SetTopThrottledKeys gets a reference to the given []GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner and assigns it to the TopThrottledKeys field.
func (o *GetRateLimitAnalytics200ResponseData) SetTopThrottledKeys(v []GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) {
	o.TopThrottledKeys = v
}

// GetTopThrottledEndpoints returns the TopThrottledEndpoints field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseData) GetTopThrottledEndpoints() []GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner {
	if o == nil || IsNil(o.TopThrottledEndpoints) {
		var ret []GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner
		return ret
	}
	return o.TopThrottledEndpoints
}

// GetTopThrottledEndpointsOk returns a tuple with the TopThrottledEndpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseData) GetTopThrottledEndpointsOk() ([]GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner, bool) {
	if o == nil || IsNil(o.TopThrottledEndpoints) {
		return nil, false
	}
	return o.TopThrottledEndpoints, true
}

// HasTopThrottledEndpoints returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseData) HasTopThrottledEndpoints() bool {
	if o != nil && !IsNil(o.TopThrottledEndpoints) {
		return true
	}

	return false
}

// SetTopThrottledEndpoints gets a reference to the given []GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner and assigns it to the TopThrottledEndpoints field.
func (o *GetRateLimitAnalytics200ResponseData) SetTopThrottledEndpoints(v []GetRateLimitAnalytics200ResponseDataTopThrottledEndpointsInner) {
	o.TopThrottledEndpoints = v
}

// GetByTier returns the ByTier field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseData) GetByTier() GetRateLimitAnalytics200ResponseDataByTier {
	if o == nil || IsNil(o.ByTier) {
		var ret GetRateLimitAnalytics200ResponseDataByTier
		return ret
	}
	return *o.ByTier
}

// GetByTierOk returns a tuple with the ByTier field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseData) GetByTierOk() (*GetRateLimitAnalytics200ResponseDataByTier, bool) {
	if o == nil || IsNil(o.ByTier) {
		return nil, false
	}
	return o.ByTier, true
}

// HasByTier returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseData) HasByTier() bool {
	if o != nil && !IsNil(o.ByTier) {
		return true
	}

	return false
}

// SetByTier gets a reference to the given GetRateLimitAnalytics200ResponseDataByTier and assigns it to the ByTier field.
func (o *GetRateLimitAnalytics200ResponseData) SetByTier(v GetRateLimitAnalytics200ResponseDataByTier) {
	o.ByTier = &v
}

func (o GetRateLimitAnalytics200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitAnalytics200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TotalRequests) {
		toSerialize["totalRequests"] = o.TotalRequests
	}
	if !IsNil(o.RateLimitHits) {
		toSerialize["rateLimitHits"] = o.RateLimitHits
	}
	if !IsNil(o.HitRate) {
		toSerialize["hitRate"] = o.HitRate
	}
	if !IsNil(o.TopThrottledKeys) {
		toSerialize["topThrottledKeys"] = o.TopThrottledKeys
	}
	if !IsNil(o.TopThrottledEndpoints) {
		toSerialize["topThrottledEndpoints"] = o.TopThrottledEndpoints
	}
	if !IsNil(o.ByTier) {
		toSerialize["byTier"] = o.ByTier
	}
	return toSerialize, nil
}

type NullableGetRateLimitAnalytics200ResponseData struct {
	value *GetRateLimitAnalytics200ResponseData
	isSet bool
}

func (v NullableGetRateLimitAnalytics200ResponseData) Get() *GetRateLimitAnalytics200ResponseData {
	return v.value
}

func (v *NullableGetRateLimitAnalytics200ResponseData) Set(val *GetRateLimitAnalytics200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitAnalytics200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitAnalytics200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitAnalytics200ResponseData(val *GetRateLimitAnalytics200ResponseData) *NullableGetRateLimitAnalytics200ResponseData {
	return &NullableGetRateLimitAnalytics200ResponseData{value: val, isSet: true}
}

func (v NullableGetRateLimitAnalytics200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitAnalytics200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


