/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GraphqlQueryRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphqlQueryRequest{}

// GraphqlQueryRequest struct for GraphqlQueryRequest
type GraphqlQueryRequest struct {
	Query *string `json:"query,omitempty"`
	Variables map[string]interface{} `json:"variables,omitempty"`
}

// NewGraphqlQueryRequest instantiates a new GraphqlQueryRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphqlQueryRequest() *GraphqlQueryRequest {
	this := GraphqlQueryRequest{}
	return &this
}

// NewGraphqlQueryRequestWithDefaults instantiates a new GraphqlQueryRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphqlQueryRequestWithDefaults() *GraphqlQueryRequest {
	this := GraphqlQueryRequest{}
	return &this
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *GraphqlQueryRequest) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphqlQueryRequest) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *GraphqlQueryRequest) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *GraphqlQueryRequest) SetQuery(v string) {
	o.Query = &v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *GraphqlQueryRequest) GetVariables() map[string]interface{} {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]interface{}
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphqlQueryRequest) GetVariablesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]interface{}{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *GraphqlQueryRequest) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]interface{} and assigns it to the Variables field.
func (o *GraphqlQueryRequest) SetVariables(v map[string]interface{}) {
	o.Variables = v
}

func (o GraphqlQueryRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphqlQueryRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

type NullableGraphqlQueryRequest struct {
	value *GraphqlQueryRequest
	isSet bool
}

func (v NullableGraphqlQueryRequest) Get() *GraphqlQueryRequest {
	return v.value
}

func (v *NullableGraphqlQueryRequest) Set(val *GraphqlQueryRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphqlQueryRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphqlQueryRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphqlQueryRequest(val *GraphqlQueryRequest) *NullableGraphqlQueryRequest {
	return &NullableGraphqlQueryRequest{value: val, isSet: true}
}

func (v NullableGraphqlQueryRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphqlQueryRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


