/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DeleteTheme200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteTheme200ResponseData{}

// DeleteTheme200ResponseData struct for DeleteTheme200ResponseData
type DeleteTheme200ResponseData struct {
	Deleted *bool `json:"deleted,omitempty"`
}

// NewDeleteTheme200ResponseData instantiates a new DeleteTheme200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteTheme200ResponseData() *DeleteTheme200ResponseData {
	this := DeleteTheme200ResponseData{}
	return &this
}

// NewDeleteTheme200ResponseDataWithDefaults instantiates a new DeleteTheme200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteTheme200ResponseDataWithDefaults() *DeleteTheme200ResponseData {
	this := DeleteTheme200ResponseData{}
	return &this
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *DeleteTheme200ResponseData) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeleteTheme200ResponseData) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *DeleteTheme200ResponseData) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *DeleteTheme200ResponseData) SetDeleted(v bool) {
	o.Deleted = &v
}

func (o DeleteTheme200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteTheme200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	return toSerialize, nil
}

type NullableDeleteTheme200ResponseData struct {
	value *DeleteTheme200ResponseData
	isSet bool
}

func (v NullableDeleteTheme200ResponseData) Get() *DeleteTheme200ResponseData {
	return v.value
}

func (v *NullableDeleteTheme200ResponseData) Set(val *DeleteTheme200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteTheme200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteTheme200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteTheme200ResponseData(val *DeleteTheme200ResponseData) *NullableDeleteTheme200ResponseData {
	return &NullableDeleteTheme200ResponseData{value: val, isSet: true}
}

func (v NullableDeleteTheme200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteTheme200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


