/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitStatus200ResponseDataResetAt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitStatus200ResponseDataResetAt{}

// GetRateLimitStatus200ResponseDataResetAt struct for GetRateLimitStatus200ResponseDataResetAt
type GetRateLimitStatus200ResponseDataResetAt struct {
	Hourly *int32 `json:"hourly,omitempty"`
	Daily *int32 `json:"daily,omitempty"`
	Monthly *int32 `json:"monthly,omitempty"`
}

// NewGetRateLimitStatus200ResponseDataResetAt instantiates a new GetRateLimitStatus200ResponseDataResetAt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitStatus200ResponseDataResetAt() *GetRateLimitStatus200ResponseDataResetAt {
	this := GetRateLimitStatus200ResponseDataResetAt{}
	return &this
}

// NewGetRateLimitStatus200ResponseDataResetAtWithDefaults instantiates a new GetRateLimitStatus200ResponseDataResetAt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitStatus200ResponseDataResetAtWithDefaults() *GetRateLimitStatus200ResponseDataResetAt {
	this := GetRateLimitStatus200ResponseDataResetAt{}
	return &this
}

// GetHourly returns the Hourly field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseDataResetAt) GetHourly() int32 {
	if o == nil || IsNil(o.Hourly) {
		var ret int32
		return ret
	}
	return *o.Hourly
}

// GetHourlyOk returns a tuple with the Hourly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseDataResetAt) GetHourlyOk() (*int32, bool) {
	if o == nil || IsNil(o.Hourly) {
		return nil, false
	}
	return o.Hourly, true
}

// HasHourly returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseDataResetAt) HasHourly() bool {
	if o != nil && !IsNil(o.Hourly) {
		return true
	}

	return false
}

// SetHourly gets a reference to the given int32 and assigns it to the Hourly field.
func (o *GetRateLimitStatus200ResponseDataResetAt) SetHourly(v int32) {
	o.Hourly = &v
}

// GetDaily returns the Daily field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseDataResetAt) GetDaily() int32 {
	if o == nil || IsNil(o.Daily) {
		var ret int32
		return ret
	}
	return *o.Daily
}

// GetDailyOk returns a tuple with the Daily field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseDataResetAt) GetDailyOk() (*int32, bool) {
	if o == nil || IsNil(o.Daily) {
		return nil, false
	}
	return o.Daily, true
}

// HasDaily returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseDataResetAt) HasDaily() bool {
	if o != nil && !IsNil(o.Daily) {
		return true
	}

	return false
}

// SetDaily gets a reference to the given int32 and assigns it to the Daily field.
func (o *GetRateLimitStatus200ResponseDataResetAt) SetDaily(v int32) {
	o.Daily = &v
}

// GetMonthly returns the Monthly field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseDataResetAt) GetMonthly() int32 {
	if o == nil || IsNil(o.Monthly) {
		var ret int32
		return ret
	}
	return *o.Monthly
}

// GetMonthlyOk returns a tuple with the Monthly field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseDataResetAt) GetMonthlyOk() (*int32, bool) {
	if o == nil || IsNil(o.Monthly) {
		return nil, false
	}
	return o.Monthly, true
}

// HasMonthly returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseDataResetAt) HasMonthly() bool {
	if o != nil && !IsNil(o.Monthly) {
		return true
	}

	return false
}

// SetMonthly gets a reference to the given int32 and assigns it to the Monthly field.
func (o *GetRateLimitStatus200ResponseDataResetAt) SetMonthly(v int32) {
	o.Monthly = &v
}

func (o GetRateLimitStatus200ResponseDataResetAt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitStatus200ResponseDataResetAt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Hourly) {
		toSerialize["hourly"] = o.Hourly
	}
	if !IsNil(o.Daily) {
		toSerialize["daily"] = o.Daily
	}
	if !IsNil(o.Monthly) {
		toSerialize["monthly"] = o.Monthly
	}
	return toSerialize, nil
}

type NullableGetRateLimitStatus200ResponseDataResetAt struct {
	value *GetRateLimitStatus200ResponseDataResetAt
	isSet bool
}

func (v NullableGetRateLimitStatus200ResponseDataResetAt) Get() *GetRateLimitStatus200ResponseDataResetAt {
	return v.value
}

func (v *NullableGetRateLimitStatus200ResponseDataResetAt) Set(val *GetRateLimitStatus200ResponseDataResetAt) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitStatus200ResponseDataResetAt) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitStatus200ResponseDataResetAt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitStatus200ResponseDataResetAt(val *GetRateLimitStatus200ResponseDataResetAt) *NullableGetRateLimitStatus200ResponseDataResetAt {
	return &NullableGetRateLimitStatus200ResponseDataResetAt{value: val, isSet: true}
}

func (v NullableGetRateLimitStatus200ResponseDataResetAt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitStatus200ResponseDataResetAt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


