/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateTheme201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTheme201Response{}

// CreateTheme201Response struct for CreateTheme201Response
type CreateTheme201Response struct {
	Success *bool `json:"success,omitempty"`
	Data *Theme `json:"data,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewCreateTheme201Response instantiates a new CreateTheme201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTheme201Response() *CreateTheme201Response {
	this := CreateTheme201Response{}
	return &this
}

// NewCreateTheme201ResponseWithDefaults instantiates a new CreateTheme201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTheme201ResponseWithDefaults() *CreateTheme201Response {
	this := CreateTheme201Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CreateTheme201Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTheme201Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CreateTheme201Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CreateTheme201Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateTheme201Response) GetData() Theme {
	if o == nil || IsNil(o.Data) {
		var ret Theme
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTheme201Response) GetDataOk() (*Theme, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateTheme201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Theme and assigns it to the Data field.
func (o *CreateTheme201Response) SetData(v Theme) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CreateTheme201Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTheme201Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreateTheme201Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CreateTheme201Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o CreateTheme201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTheme201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableCreateTheme201Response struct {
	value *CreateTheme201Response
	isSet bool
}

func (v NullableCreateTheme201Response) Get() *CreateTheme201Response {
	return v.value
}

func (v *NullableCreateTheme201Response) Set(val *CreateTheme201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTheme201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTheme201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTheme201Response(val *CreateTheme201Response) *NullableCreateTheme201Response {
	return &NullableCreateTheme201Response{value: val, isSet: true}
}

func (v NullableCreateTheme201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTheme201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


