/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PurgeUserCache200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PurgeUserCache200Response{}

// PurgeUserCache200Response struct for PurgeUserCache200Response
type PurgeUserCache200Response struct {
	Success *bool `json:"success,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewPurgeUserCache200Response instantiates a new PurgeUserCache200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPurgeUserCache200Response() *PurgeUserCache200Response {
	this := PurgeUserCache200Response{}
	return &this
}

// NewPurgeUserCache200ResponseWithDefaults instantiates a new PurgeUserCache200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPurgeUserCache200ResponseWithDefaults() *PurgeUserCache200Response {
	this := PurgeUserCache200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *PurgeUserCache200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurgeUserCache200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *PurgeUserCache200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *PurgeUserCache200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *PurgeUserCache200Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PurgeUserCache200Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *PurgeUserCache200Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *PurgeUserCache200Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o PurgeUserCache200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PurgeUserCache200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullablePurgeUserCache200Response struct {
	value *PurgeUserCache200Response
	isSet bool
}

func (v NullablePurgeUserCache200Response) Get() *PurgeUserCache200Response {
	return v.value
}

func (v *NullablePurgeUserCache200Response) Set(val *PurgeUserCache200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePurgeUserCache200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePurgeUserCache200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePurgeUserCache200Response(val *PurgeUserCache200Response) *NullablePurgeUserCache200Response {
	return &NullablePurgeUserCache200Response{value: val, isSet: true}
}

func (v NullablePurgeUserCache200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePurgeUserCache200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


