/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetFeatures200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetFeatures200Response{}

// GetFeatures200Response struct for GetFeatures200Response
type GetFeatures200Response struct {
	Success *bool `json:"success,omitempty"`
	Data []Feature `json:"data,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewGetFeatures200Response instantiates a new GetFeatures200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetFeatures200Response() *GetFeatures200Response {
	this := GetFeatures200Response{}
	return &this
}

// NewGetFeatures200ResponseWithDefaults instantiates a new GetFeatures200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetFeatures200ResponseWithDefaults() *GetFeatures200Response {
	this := GetFeatures200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *GetFeatures200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFeatures200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *GetFeatures200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *GetFeatures200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetFeatures200Response) GetData() []Feature {
	if o == nil || IsNil(o.Data) {
		var ret []Feature
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFeatures200Response) GetDataOk() ([]Feature, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetFeatures200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Feature and assigns it to the Data field.
func (o *GetFeatures200Response) SetData(v []Feature) {
	o.Data = v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *GetFeatures200Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetFeatures200Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *GetFeatures200Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *GetFeatures200Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o GetFeatures200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetFeatures200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableGetFeatures200Response struct {
	value *GetFeatures200Response
	isSet bool
}

func (v NullableGetFeatures200Response) Get() *GetFeatures200Response {
	return v.value
}

func (v *NullableGetFeatures200Response) Set(val *GetFeatures200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetFeatures200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetFeatures200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetFeatures200Response(val *GetFeatures200Response) *NullableGetFeatures200Response {
	return &NullableGetFeatures200Response{value: val, isSet: true}
}

func (v NullableGetFeatures200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetFeatures200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


