/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitStatus200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitStatus200ResponseData{}

// GetRateLimitStatus200ResponseData struct for GetRateLimitStatus200ResponseData
type GetRateLimitStatus200ResponseData struct {
	Limits *GetRateLimitStatus200ResponseDataLimits `json:"limits,omitempty"`
	Current *GetRateLimitStatus200ResponseDataCurrent `json:"current,omitempty"`
	Remaining *GetRateLimitStatus200ResponseDataCurrent `json:"remaining,omitempty"`
	ResetAt *GetRateLimitStatus200ResponseDataResetAt `json:"resetAt,omitempty"`
}

// NewGetRateLimitStatus200ResponseData instantiates a new GetRateLimitStatus200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitStatus200ResponseData() *GetRateLimitStatus200ResponseData {
	this := GetRateLimitStatus200ResponseData{}
	return &this
}

// NewGetRateLimitStatus200ResponseDataWithDefaults instantiates a new GetRateLimitStatus200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitStatus200ResponseDataWithDefaults() *GetRateLimitStatus200ResponseData {
	this := GetRateLimitStatus200ResponseData{}
	return &this
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseData) GetLimits() GetRateLimitStatus200ResponseDataLimits {
	if o == nil || IsNil(o.Limits) {
		var ret GetRateLimitStatus200ResponseDataLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseData) GetLimitsOk() (*GetRateLimitStatus200ResponseDataLimits, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseData) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given GetRateLimitStatus200ResponseDataLimits and assigns it to the Limits field.
func (o *GetRateLimitStatus200ResponseData) SetLimits(v GetRateLimitStatus200ResponseDataLimits) {
	o.Limits = &v
}

// GetCurrent returns the Current field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseData) GetCurrent() GetRateLimitStatus200ResponseDataCurrent {
	if o == nil || IsNil(o.Current) {
		var ret GetRateLimitStatus200ResponseDataCurrent
		return ret
	}
	return *o.Current
}

// GetCurrentOk returns a tuple with the Current field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseData) GetCurrentOk() (*GetRateLimitStatus200ResponseDataCurrent, bool) {
	if o == nil || IsNil(o.Current) {
		return nil, false
	}
	return o.Current, true
}

// HasCurrent returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseData) HasCurrent() bool {
	if o != nil && !IsNil(o.Current) {
		return true
	}

	return false
}

// SetCurrent gets a reference to the given GetRateLimitStatus200ResponseDataCurrent and assigns it to the Current field.
func (o *GetRateLimitStatus200ResponseData) SetCurrent(v GetRateLimitStatus200ResponseDataCurrent) {
	o.Current = &v
}

// GetRemaining returns the Remaining field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseData) GetRemaining() GetRateLimitStatus200ResponseDataCurrent {
	if o == nil || IsNil(o.Remaining) {
		var ret GetRateLimitStatus200ResponseDataCurrent
		return ret
	}
	return *o.Remaining
}

// GetRemainingOk returns a tuple with the Remaining field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseData) GetRemainingOk() (*GetRateLimitStatus200ResponseDataCurrent, bool) {
	if o == nil || IsNil(o.Remaining) {
		return nil, false
	}
	return o.Remaining, true
}

// HasRemaining returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseData) HasRemaining() bool {
	if o != nil && !IsNil(o.Remaining) {
		return true
	}

	return false
}

// SetRemaining gets a reference to the given GetRateLimitStatus200ResponseDataCurrent and assigns it to the Remaining field.
func (o *GetRateLimitStatus200ResponseData) SetRemaining(v GetRateLimitStatus200ResponseDataCurrent) {
	o.Remaining = &v
}

// GetResetAt returns the ResetAt field value if set, zero value otherwise.
func (o *GetRateLimitStatus200ResponseData) GetResetAt() GetRateLimitStatus200ResponseDataResetAt {
	if o == nil || IsNil(o.ResetAt) {
		var ret GetRateLimitStatus200ResponseDataResetAt
		return ret
	}
	return *o.ResetAt
}

// GetResetAtOk returns a tuple with the ResetAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitStatus200ResponseData) GetResetAtOk() (*GetRateLimitStatus200ResponseDataResetAt, bool) {
	if o == nil || IsNil(o.ResetAt) {
		return nil, false
	}
	return o.ResetAt, true
}

// HasResetAt returns a boolean if a field has been set.
func (o *GetRateLimitStatus200ResponseData) HasResetAt() bool {
	if o != nil && !IsNil(o.ResetAt) {
		return true
	}

	return false
}

// SetResetAt gets a reference to the given GetRateLimitStatus200ResponseDataResetAt and assigns it to the ResetAt field.
func (o *GetRateLimitStatus200ResponseData) SetResetAt(v GetRateLimitStatus200ResponseDataResetAt) {
	o.ResetAt = &v
}

func (o GetRateLimitStatus200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitStatus200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	if !IsNil(o.Current) {
		toSerialize["current"] = o.Current
	}
	if !IsNil(o.Remaining) {
		toSerialize["remaining"] = o.Remaining
	}
	if !IsNil(o.ResetAt) {
		toSerialize["resetAt"] = o.ResetAt
	}
	return toSerialize, nil
}

type NullableGetRateLimitStatus200ResponseData struct {
	value *GetRateLimitStatus200ResponseData
	isSet bool
}

func (v NullableGetRateLimitStatus200ResponseData) Get() *GetRateLimitStatus200ResponseData {
	return v.value
}

func (v *NullableGetRateLimitStatus200ResponseData) Set(val *GetRateLimitStatus200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitStatus200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitStatus200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitStatus200ResponseData(val *GetRateLimitStatus200ResponseData) *NullableGetRateLimitStatus200ResponseData {
	return &NullableGetRateLimitStatus200ResponseData{value: val, isSet: true}
}

func (v NullableGetRateLimitStatus200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitStatus200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


