/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SetCustomRateLimitsRequestLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetCustomRateLimitsRequestLimits{}

// SetCustomRateLimitsRequestLimits struct for SetCustomRateLimitsRequestLimits
type SetCustomRateLimitsRequestLimits struct {
	HourlyLimit *int32 `json:"hourlyLimit,omitempty"`
	DailyLimit *int32 `json:"dailyLimit,omitempty"`
	MonthlyLimit *int32 `json:"monthlyLimit,omitempty"`
	BurstLimit *int32 `json:"burstLimit,omitempty"`
	ConcurrentLimit *int32 `json:"concurrentLimit,omitempty"`
}

// NewSetCustomRateLimitsRequestLimits instantiates a new SetCustomRateLimitsRequestLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetCustomRateLimitsRequestLimits() *SetCustomRateLimitsRequestLimits {
	this := SetCustomRateLimitsRequestLimits{}
	return &this
}

// NewSetCustomRateLimitsRequestLimitsWithDefaults instantiates a new SetCustomRateLimitsRequestLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetCustomRateLimitsRequestLimitsWithDefaults() *SetCustomRateLimitsRequestLimits {
	this := SetCustomRateLimitsRequestLimits{}
	return &this
}

// GetHourlyLimit returns the HourlyLimit field value if set, zero value otherwise.
func (o *SetCustomRateLimitsRequestLimits) GetHourlyLimit() int32 {
	if o == nil || IsNil(o.HourlyLimit) {
		var ret int32
		return ret
	}
	return *o.HourlyLimit
}

// GetHourlyLimitOk returns a tuple with the HourlyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCustomRateLimitsRequestLimits) GetHourlyLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.HourlyLimit) {
		return nil, false
	}
	return o.HourlyLimit, true
}

// HasHourlyLimit returns a boolean if a field has been set.
func (o *SetCustomRateLimitsRequestLimits) HasHourlyLimit() bool {
	if o != nil && !IsNil(o.HourlyLimit) {
		return true
	}

	return false
}

// SetHourlyLimit gets a reference to the given int32 and assigns it to the HourlyLimit field.
func (o *SetCustomRateLimitsRequestLimits) SetHourlyLimit(v int32) {
	o.HourlyLimit = &v
}

// GetDailyLimit returns the DailyLimit field value if set, zero value otherwise.
func (o *SetCustomRateLimitsRequestLimits) GetDailyLimit() int32 {
	if o == nil || IsNil(o.DailyLimit) {
		var ret int32
		return ret
	}
	return *o.DailyLimit
}

// GetDailyLimitOk returns a tuple with the DailyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCustomRateLimitsRequestLimits) GetDailyLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.DailyLimit) {
		return nil, false
	}
	return o.DailyLimit, true
}

// HasDailyLimit returns a boolean if a field has been set.
func (o *SetCustomRateLimitsRequestLimits) HasDailyLimit() bool {
	if o != nil && !IsNil(o.DailyLimit) {
		return true
	}

	return false
}

// SetDailyLimit gets a reference to the given int32 and assigns it to the DailyLimit field.
func (o *SetCustomRateLimitsRequestLimits) SetDailyLimit(v int32) {
	o.DailyLimit = &v
}

// GetMonthlyLimit returns the MonthlyLimit field value if set, zero value otherwise.
func (o *SetCustomRateLimitsRequestLimits) GetMonthlyLimit() int32 {
	if o == nil || IsNil(o.MonthlyLimit) {
		var ret int32
		return ret
	}
	return *o.MonthlyLimit
}

// GetMonthlyLimitOk returns a tuple with the MonthlyLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCustomRateLimitsRequestLimits) GetMonthlyLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.MonthlyLimit) {
		return nil, false
	}
	return o.MonthlyLimit, true
}

// HasMonthlyLimit returns a boolean if a field has been set.
func (o *SetCustomRateLimitsRequestLimits) HasMonthlyLimit() bool {
	if o != nil && !IsNil(o.MonthlyLimit) {
		return true
	}

	return false
}

// SetMonthlyLimit gets a reference to the given int32 and assigns it to the MonthlyLimit field.
func (o *SetCustomRateLimitsRequestLimits) SetMonthlyLimit(v int32) {
	o.MonthlyLimit = &v
}

// GetBurstLimit returns the BurstLimit field value if set, zero value otherwise.
func (o *SetCustomRateLimitsRequestLimits) GetBurstLimit() int32 {
	if o == nil || IsNil(o.BurstLimit) {
		var ret int32
		return ret
	}
	return *o.BurstLimit
}

// GetBurstLimitOk returns a tuple with the BurstLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCustomRateLimitsRequestLimits) GetBurstLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.BurstLimit) {
		return nil, false
	}
	return o.BurstLimit, true
}

// HasBurstLimit returns a boolean if a field has been set.
func (o *SetCustomRateLimitsRequestLimits) HasBurstLimit() bool {
	if o != nil && !IsNil(o.BurstLimit) {
		return true
	}

	return false
}

// SetBurstLimit gets a reference to the given int32 and assigns it to the BurstLimit field.
func (o *SetCustomRateLimitsRequestLimits) SetBurstLimit(v int32) {
	o.BurstLimit = &v
}

// GetConcurrentLimit returns the ConcurrentLimit field value if set, zero value otherwise.
func (o *SetCustomRateLimitsRequestLimits) GetConcurrentLimit() int32 {
	if o == nil || IsNil(o.ConcurrentLimit) {
		var ret int32
		return ret
	}
	return *o.ConcurrentLimit
}

// GetConcurrentLimitOk returns a tuple with the ConcurrentLimit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCustomRateLimitsRequestLimits) GetConcurrentLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.ConcurrentLimit) {
		return nil, false
	}
	return o.ConcurrentLimit, true
}

// HasConcurrentLimit returns a boolean if a field has been set.
func (o *SetCustomRateLimitsRequestLimits) HasConcurrentLimit() bool {
	if o != nil && !IsNil(o.ConcurrentLimit) {
		return true
	}

	return false
}

// SetConcurrentLimit gets a reference to the given int32 and assigns it to the ConcurrentLimit field.
func (o *SetCustomRateLimitsRequestLimits) SetConcurrentLimit(v int32) {
	o.ConcurrentLimit = &v
}

func (o SetCustomRateLimitsRequestLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetCustomRateLimitsRequestLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HourlyLimit) {
		toSerialize["hourlyLimit"] = o.HourlyLimit
	}
	if !IsNil(o.DailyLimit) {
		toSerialize["dailyLimit"] = o.DailyLimit
	}
	if !IsNil(o.MonthlyLimit) {
		toSerialize["monthlyLimit"] = o.MonthlyLimit
	}
	if !IsNil(o.BurstLimit) {
		toSerialize["burstLimit"] = o.BurstLimit
	}
	if !IsNil(o.ConcurrentLimit) {
		toSerialize["concurrentLimit"] = o.ConcurrentLimit
	}
	return toSerialize, nil
}

type NullableSetCustomRateLimitsRequestLimits struct {
	value *SetCustomRateLimitsRequestLimits
	isSet bool
}

func (v NullableSetCustomRateLimitsRequestLimits) Get() *SetCustomRateLimitsRequestLimits {
	return v.value
}

func (v *NullableSetCustomRateLimitsRequestLimits) Set(val *SetCustomRateLimitsRequestLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableSetCustomRateLimitsRequestLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableSetCustomRateLimitsRequestLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetCustomRateLimitsRequestLimits(val *SetCustomRateLimitsRequestLimits) *NullableSetCustomRateLimitsRequestLimits {
	return &NullableSetCustomRateLimitsRequestLimits{value: val, isSet: true}
}

func (v NullableSetCustomRateLimitsRequestLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetCustomRateLimitsRequestLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


