/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ManageBypass200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageBypass200ResponseData{}

// ManageBypass200ResponseData struct for ManageBypass200ResponseData
type ManageBypass200ResponseData struct {
	BypassKeys []string `json:"bypassKeys,omitempty"`
	BypassUsers []string `json:"bypassUsers,omitempty"`
}

// NewManageBypass200ResponseData instantiates a new ManageBypass200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageBypass200ResponseData() *ManageBypass200ResponseData {
	this := ManageBypass200ResponseData{}
	return &this
}

// NewManageBypass200ResponseDataWithDefaults instantiates a new ManageBypass200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageBypass200ResponseDataWithDefaults() *ManageBypass200ResponseData {
	this := ManageBypass200ResponseData{}
	return &this
}

// GetBypassKeys returns the BypassKeys field value if set, zero value otherwise.
func (o *ManageBypass200ResponseData) GetBypassKeys() []string {
	if o == nil || IsNil(o.BypassKeys) {
		var ret []string
		return ret
	}
	return o.BypassKeys
}

// GetBypassKeysOk returns a tuple with the BypassKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageBypass200ResponseData) GetBypassKeysOk() ([]string, bool) {
	if o == nil || IsNil(o.BypassKeys) {
		return nil, false
	}
	return o.BypassKeys, true
}

// HasBypassKeys returns a boolean if a field has been set.
func (o *ManageBypass200ResponseData) HasBypassKeys() bool {
	if o != nil && !IsNil(o.BypassKeys) {
		return true
	}

	return false
}

// SetBypassKeys gets a reference to the given []string and assigns it to the BypassKeys field.
func (o *ManageBypass200ResponseData) SetBypassKeys(v []string) {
	o.BypassKeys = v
}

// GetBypassUsers returns the BypassUsers field value if set, zero value otherwise.
func (o *ManageBypass200ResponseData) GetBypassUsers() []string {
	if o == nil || IsNil(o.BypassUsers) {
		var ret []string
		return ret
	}
	return o.BypassUsers
}

// GetBypassUsersOk returns a tuple with the BypassUsers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageBypass200ResponseData) GetBypassUsersOk() ([]string, bool) {
	if o == nil || IsNil(o.BypassUsers) {
		return nil, false
	}
	return o.BypassUsers, true
}

// HasBypassUsers returns a boolean if a field has been set.
func (o *ManageBypass200ResponseData) HasBypassUsers() bool {
	if o != nil && !IsNil(o.BypassUsers) {
		return true
	}

	return false
}

// SetBypassUsers gets a reference to the given []string and assigns it to the BypassUsers field.
func (o *ManageBypass200ResponseData) SetBypassUsers(v []string) {
	o.BypassUsers = v
}

func (o ManageBypass200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageBypass200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BypassKeys) {
		toSerialize["bypassKeys"] = o.BypassKeys
	}
	if !IsNil(o.BypassUsers) {
		toSerialize["bypassUsers"] = o.BypassUsers
	}
	return toSerialize, nil
}

type NullableManageBypass200ResponseData struct {
	value *ManageBypass200ResponseData
	isSet bool
}

func (v NullableManageBypass200ResponseData) Get() *ManageBypass200ResponseData {
	return v.value
}

func (v *NullableManageBypass200ResponseData) Set(val *ManageBypass200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableManageBypass200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableManageBypass200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageBypass200ResponseData(val *ManageBypass200ResponseData) *NullableManageBypass200ResponseData {
	return &NullableManageBypass200ResponseData{value: val, isSet: true}
}

func (v NullableManageBypass200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageBypass200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


