/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitAnalytics200ResponseDataByTierFREE type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitAnalytics200ResponseDataByTierFREE{}

// GetRateLimitAnalytics200ResponseDataByTierFREE struct for GetRateLimitAnalytics200ResponseDataByTierFREE
type GetRateLimitAnalytics200ResponseDataByTierFREE struct {
	Requests *int32 `json:"requests,omitempty"`
	Hits *int32 `json:"hits,omitempty"`
	HitRate *float32 `json:"hitRate,omitempty"`
}

// NewGetRateLimitAnalytics200ResponseDataByTierFREE instantiates a new GetRateLimitAnalytics200ResponseDataByTierFREE object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitAnalytics200ResponseDataByTierFREE() *GetRateLimitAnalytics200ResponseDataByTierFREE {
	this := GetRateLimitAnalytics200ResponseDataByTierFREE{}
	return &this
}

// NewGetRateLimitAnalytics200ResponseDataByTierFREEWithDefaults instantiates a new GetRateLimitAnalytics200ResponseDataByTierFREE object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitAnalytics200ResponseDataByTierFREEWithDefaults() *GetRateLimitAnalytics200ResponseDataByTierFREE {
	this := GetRateLimitAnalytics200ResponseDataByTierFREE{}
	return &this
}

// GetRequests returns the Requests field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) GetRequests() int32 {
	if o == nil || IsNil(o.Requests) {
		var ret int32
		return ret
	}
	return *o.Requests
}

// GetRequestsOk returns a tuple with the Requests field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) GetRequestsOk() (*int32, bool) {
	if o == nil || IsNil(o.Requests) {
		return nil, false
	}
	return o.Requests, true
}

// HasRequests returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) HasRequests() bool {
	if o != nil && !IsNil(o.Requests) {
		return true
	}

	return false
}

// SetRequests gets a reference to the given int32 and assigns it to the Requests field.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) SetRequests(v int32) {
	o.Requests = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) GetHits() int32 {
	if o == nil || IsNil(o.Hits) {
		var ret int32
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) GetHitsOk() (*int32, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given int32 and assigns it to the Hits field.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) SetHits(v int32) {
	o.Hits = &v
}

// GetHitRate returns the HitRate field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) GetHitRate() float32 {
	if o == nil || IsNil(o.HitRate) {
		var ret float32
		return ret
	}
	return *o.HitRate
}

// GetHitRateOk returns a tuple with the HitRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) GetHitRateOk() (*float32, bool) {
	if o == nil || IsNil(o.HitRate) {
		return nil, false
	}
	return o.HitRate, true
}

// HasHitRate returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) HasHitRate() bool {
	if o != nil && !IsNil(o.HitRate) {
		return true
	}

	return false
}

// SetHitRate gets a reference to the given float32 and assigns it to the HitRate field.
func (o *GetRateLimitAnalytics200ResponseDataByTierFREE) SetHitRate(v float32) {
	o.HitRate = &v
}

func (o GetRateLimitAnalytics200ResponseDataByTierFREE) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitAnalytics200ResponseDataByTierFREE) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Requests) {
		toSerialize["requests"] = o.Requests
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	if !IsNil(o.HitRate) {
		toSerialize["hitRate"] = o.HitRate
	}
	return toSerialize, nil
}

type NullableGetRateLimitAnalytics200ResponseDataByTierFREE struct {
	value *GetRateLimitAnalytics200ResponseDataByTierFREE
	isSet bool
}

func (v NullableGetRateLimitAnalytics200ResponseDataByTierFREE) Get() *GetRateLimitAnalytics200ResponseDataByTierFREE {
	return v.value
}

func (v *NullableGetRateLimitAnalytics200ResponseDataByTierFREE) Set(val *GetRateLimitAnalytics200ResponseDataByTierFREE) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitAnalytics200ResponseDataByTierFREE) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitAnalytics200ResponseDataByTierFREE) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitAnalytics200ResponseDataByTierFREE(val *GetRateLimitAnalytics200ResponseDataByTierFREE) *NullableGetRateLimitAnalytics200ResponseDataByTierFREE {
	return &NullableGetRateLimitAnalytics200ResponseDataByTierFREE{value: val, isSet: true}
}

func (v NullableGetRateLimitAnalytics200ResponseDataByTierFREE) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitAnalytics200ResponseDataByTierFREE) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


