/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GraphqlQuery200ResponseErrorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GraphqlQuery200ResponseErrorsInner{}

// GraphqlQuery200ResponseErrorsInner struct for GraphqlQuery200ResponseErrorsInner
type GraphqlQuery200ResponseErrorsInner struct {
	Message *string `json:"message,omitempty"`
}

// NewGraphqlQuery200ResponseErrorsInner instantiates a new GraphqlQuery200ResponseErrorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphqlQuery200ResponseErrorsInner() *GraphqlQuery200ResponseErrorsInner {
	this := GraphqlQuery200ResponseErrorsInner{}
	return &this
}

// NewGraphqlQuery200ResponseErrorsInnerWithDefaults instantiates a new GraphqlQuery200ResponseErrorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphqlQuery200ResponseErrorsInnerWithDefaults() *GraphqlQuery200ResponseErrorsInner {
	this := GraphqlQuery200ResponseErrorsInner{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GraphqlQuery200ResponseErrorsInner) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphqlQuery200ResponseErrorsInner) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GraphqlQuery200ResponseErrorsInner) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GraphqlQuery200ResponseErrorsInner) SetMessage(v string) {
	o.Message = &v
}

func (o GraphqlQuery200ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GraphqlQuery200ResponseErrorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGraphqlQuery200ResponseErrorsInner struct {
	value *GraphqlQuery200ResponseErrorsInner
	isSet bool
}

func (v NullableGraphqlQuery200ResponseErrorsInner) Get() *GraphqlQuery200ResponseErrorsInner {
	return v.value
}

func (v *NullableGraphqlQuery200ResponseErrorsInner) Set(val *GraphqlQuery200ResponseErrorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphqlQuery200ResponseErrorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphqlQuery200ResponseErrorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphqlQuery200ResponseErrorsInner(val *GraphqlQuery200ResponseErrorsInner) *NullableGraphqlQuery200ResponseErrorsInner {
	return &NullableGraphqlQuery200ResponseErrorsInner{value: val, isSet: true}
}

func (v NullableGraphqlQuery200ResponseErrorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphqlQuery200ResponseErrorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


