/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitAnalytics200ResponseDataByTier type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitAnalytics200ResponseDataByTier{}

// GetRateLimitAnalytics200ResponseDataByTier struct for GetRateLimitAnalytics200ResponseDataByTier
type GetRateLimitAnalytics200ResponseDataByTier struct {
	FREE *GetRateLimitAnalytics200ResponseDataByTierFREE `json:"FREE,omitempty"`
	BASIC *GetRateLimitAnalytics200ResponseDataByTierFREE `json:"BASIC,omitempty"`
	PREMIUM *GetRateLimitAnalytics200ResponseDataByTierFREE `json:"PREMIUM,omitempty"`
	ENTERPRISE *GetRateLimitAnalytics200ResponseDataByTierFREE `json:"ENTERPRISE,omitempty"`
}

// NewGetRateLimitAnalytics200ResponseDataByTier instantiates a new GetRateLimitAnalytics200ResponseDataByTier object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitAnalytics200ResponseDataByTier() *GetRateLimitAnalytics200ResponseDataByTier {
	this := GetRateLimitAnalytics200ResponseDataByTier{}
	return &this
}

// NewGetRateLimitAnalytics200ResponseDataByTierWithDefaults instantiates a new GetRateLimitAnalytics200ResponseDataByTier object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitAnalytics200ResponseDataByTierWithDefaults() *GetRateLimitAnalytics200ResponseDataByTier {
	this := GetRateLimitAnalytics200ResponseDataByTier{}
	return &this
}

// GetFREE returns the FREE field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetFREE() GetRateLimitAnalytics200ResponseDataByTierFREE {
	if o == nil || IsNil(o.FREE) {
		var ret GetRateLimitAnalytics200ResponseDataByTierFREE
		return ret
	}
	return *o.FREE
}

// GetFREEOk returns a tuple with the FREE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetFREEOk() (*GetRateLimitAnalytics200ResponseDataByTierFREE, bool) {
	if o == nil || IsNil(o.FREE) {
		return nil, false
	}
	return o.FREE, true
}

// HasFREE returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) HasFREE() bool {
	if o != nil && !IsNil(o.FREE) {
		return true
	}

	return false
}

// SetFREE gets a reference to the given GetRateLimitAnalytics200ResponseDataByTierFREE and assigns it to the FREE field.
func (o *GetRateLimitAnalytics200ResponseDataByTier) SetFREE(v GetRateLimitAnalytics200ResponseDataByTierFREE) {
	o.FREE = &v
}

// GetBASIC returns the BASIC field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetBASIC() GetRateLimitAnalytics200ResponseDataByTierFREE {
	if o == nil || IsNil(o.BASIC) {
		var ret GetRateLimitAnalytics200ResponseDataByTierFREE
		return ret
	}
	return *o.BASIC
}

// GetBASICOk returns a tuple with the BASIC field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetBASICOk() (*GetRateLimitAnalytics200ResponseDataByTierFREE, bool) {
	if o == nil || IsNil(o.BASIC) {
		return nil, false
	}
	return o.BASIC, true
}

// HasBASIC returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) HasBASIC() bool {
	if o != nil && !IsNil(o.BASIC) {
		return true
	}

	return false
}

// SetBASIC gets a reference to the given GetRateLimitAnalytics200ResponseDataByTierFREE and assigns it to the BASIC field.
func (o *GetRateLimitAnalytics200ResponseDataByTier) SetBASIC(v GetRateLimitAnalytics200ResponseDataByTierFREE) {
	o.BASIC = &v
}

// GetPREMIUM returns the PREMIUM field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetPREMIUM() GetRateLimitAnalytics200ResponseDataByTierFREE {
	if o == nil || IsNil(o.PREMIUM) {
		var ret GetRateLimitAnalytics200ResponseDataByTierFREE
		return ret
	}
	return *o.PREMIUM
}

// GetPREMIUMOk returns a tuple with the PREMIUM field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetPREMIUMOk() (*GetRateLimitAnalytics200ResponseDataByTierFREE, bool) {
	if o == nil || IsNil(o.PREMIUM) {
		return nil, false
	}
	return o.PREMIUM, true
}

// HasPREMIUM returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) HasPREMIUM() bool {
	if o != nil && !IsNil(o.PREMIUM) {
		return true
	}

	return false
}

// SetPREMIUM gets a reference to the given GetRateLimitAnalytics200ResponseDataByTierFREE and assigns it to the PREMIUM field.
func (o *GetRateLimitAnalytics200ResponseDataByTier) SetPREMIUM(v GetRateLimitAnalytics200ResponseDataByTierFREE) {
	o.PREMIUM = &v
}

// GetENTERPRISE returns the ENTERPRISE field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetENTERPRISE() GetRateLimitAnalytics200ResponseDataByTierFREE {
	if o == nil || IsNil(o.ENTERPRISE) {
		var ret GetRateLimitAnalytics200ResponseDataByTierFREE
		return ret
	}
	return *o.ENTERPRISE
}

// GetENTERPRISEOk returns a tuple with the ENTERPRISE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) GetENTERPRISEOk() (*GetRateLimitAnalytics200ResponseDataByTierFREE, bool) {
	if o == nil || IsNil(o.ENTERPRISE) {
		return nil, false
	}
	return o.ENTERPRISE, true
}

// HasENTERPRISE returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataByTier) HasENTERPRISE() bool {
	if o != nil && !IsNil(o.ENTERPRISE) {
		return true
	}

	return false
}

// SetENTERPRISE gets a reference to the given GetRateLimitAnalytics200ResponseDataByTierFREE and assigns it to the ENTERPRISE field.
func (o *GetRateLimitAnalytics200ResponseDataByTier) SetENTERPRISE(v GetRateLimitAnalytics200ResponseDataByTierFREE) {
	o.ENTERPRISE = &v
}

func (o GetRateLimitAnalytics200ResponseDataByTier) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitAnalytics200ResponseDataByTier) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FREE) {
		toSerialize["FREE"] = o.FREE
	}
	if !IsNil(o.BASIC) {
		toSerialize["BASIC"] = o.BASIC
	}
	if !IsNil(o.PREMIUM) {
		toSerialize["PREMIUM"] = o.PREMIUM
	}
	if !IsNil(o.ENTERPRISE) {
		toSerialize["ENTERPRISE"] = o.ENTERPRISE
	}
	return toSerialize, nil
}

type NullableGetRateLimitAnalytics200ResponseDataByTier struct {
	value *GetRateLimitAnalytics200ResponseDataByTier
	isSet bool
}

func (v NullableGetRateLimitAnalytics200ResponseDataByTier) Get() *GetRateLimitAnalytics200ResponseDataByTier {
	return v.value
}

func (v *NullableGetRateLimitAnalytics200ResponseDataByTier) Set(val *GetRateLimitAnalytics200ResponseDataByTier) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitAnalytics200ResponseDataByTier) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitAnalytics200ResponseDataByTier) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitAnalytics200ResponseDataByTier(val *GetRateLimitAnalytics200ResponseDataByTier) *NullableGetRateLimitAnalytics200ResponseDataByTier {
	return &NullableGetRateLimitAnalytics200ResponseDataByTier{value: val, isSet: true}
}

func (v NullableGetRateLimitAnalytics200ResponseDataByTier) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitAnalytics200ResponseDataByTier) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


