/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner{}

// GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner struct for GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner
type GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner struct {
	Key *string `json:"key,omitempty"`
	Hits *int32 `json:"hits,omitempty"`
}

// NewGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner instantiates a new GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner() *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner {
	this := GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner{}
	return &this
}

// NewGetRateLimitAnalytics200ResponseDataTopThrottledKeysInnerWithDefaults instantiates a new GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRateLimitAnalytics200ResponseDataTopThrottledKeysInnerWithDefaults() *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner {
	this := GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner{}
	return &this
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) SetKey(v string) {
	o.Key = &v
}

// GetHits returns the Hits field value if set, zero value otherwise.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) GetHits() int32 {
	if o == nil || IsNil(o.Hits) {
		var ret int32
		return ret
	}
	return *o.Hits
}

// GetHitsOk returns a tuple with the Hits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) GetHitsOk() (*int32, bool) {
	if o == nil || IsNil(o.Hits) {
		return nil, false
	}
	return o.Hits, true
}

// HasHits returns a boolean if a field has been set.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) HasHits() bool {
	if o != nil && !IsNil(o.Hits) {
		return true
	}

	return false
}

// SetHits gets a reference to the given int32 and assigns it to the Hits field.
func (o *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) SetHits(v int32) {
	o.Hits = &v
}

func (o GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.Hits) {
		toSerialize["hits"] = o.Hits
	}
	return toSerialize, nil
}

type NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner struct {
	value *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner
	isSet bool
}

func (v NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) Get() *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner {
	return v.value
}

func (v *NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) Set(val *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner(val *GetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) *NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner {
	return &NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner{value: val, isSet: true}
}

func (v NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRateLimitAnalytics200ResponseDataTopThrottledKeysInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


