/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetHealth200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetHealth200Response{}

// GetHealth200Response struct for GetHealth200Response
type GetHealth200Response struct {
	Status *string `json:"status,omitempty"`
	PlanCache *string `json:"planCache,omitempty"`
}

// NewGetHealth200Response instantiates a new GetHealth200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHealth200Response() *GetHealth200Response {
	this := GetHealth200Response{}
	return &this
}

// NewGetHealth200ResponseWithDefaults instantiates a new GetHealth200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHealth200ResponseWithDefaults() *GetHealth200Response {
	this := GetHealth200Response{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetHealth200Response) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200Response) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetHealth200Response) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetHealth200Response) SetStatus(v string) {
	o.Status = &v
}

// GetPlanCache returns the PlanCache field value if set, zero value otherwise.
func (o *GetHealth200Response) GetPlanCache() string {
	if o == nil || IsNil(o.PlanCache) {
		var ret string
		return ret
	}
	return *o.PlanCache
}

// GetPlanCacheOk returns a tuple with the PlanCache field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHealth200Response) GetPlanCacheOk() (*string, bool) {
	if o == nil || IsNil(o.PlanCache) {
		return nil, false
	}
	return o.PlanCache, true
}

// HasPlanCache returns a boolean if a field has been set.
func (o *GetHealth200Response) HasPlanCache() bool {
	if o != nil && !IsNil(o.PlanCache) {
		return true
	}

	return false
}

// SetPlanCache gets a reference to the given string and assigns it to the PlanCache field.
func (o *GetHealth200Response) SetPlanCache(v string) {
	o.PlanCache = &v
}

func (o GetHealth200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetHealth200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.PlanCache) {
		toSerialize["planCache"] = o.PlanCache
	}
	return toSerialize, nil
}

type NullableGetHealth200Response struct {
	value *GetHealth200Response
	isSet bool
}

func (v NullableGetHealth200Response) Get() *GetHealth200Response {
	return v.value
}

func (v *NullableGetHealth200Response) Set(val *GetHealth200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHealth200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHealth200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHealth200Response(val *GetHealth200Response) *NullableGetHealth200Response {
	return &NullableGetHealth200Response{value: val, isSet: true}
}

func (v NullableGetHealth200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHealth200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


