/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ManageBypass200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ManageBypass200Response{}

// ManageBypass200Response struct for ManageBypass200Response
type ManageBypass200Response struct {
	Success *bool `json:"success,omitempty"`
	Data *ManageBypass200ResponseData `json:"data,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewManageBypass200Response instantiates a new ManageBypass200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewManageBypass200Response() *ManageBypass200Response {
	this := ManageBypass200Response{}
	return &this
}

// NewManageBypass200ResponseWithDefaults instantiates a new ManageBypass200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewManageBypass200ResponseWithDefaults() *ManageBypass200Response {
	this := ManageBypass200Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *ManageBypass200Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageBypass200Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *ManageBypass200Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *ManageBypass200Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ManageBypass200Response) GetData() ManageBypass200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret ManageBypass200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageBypass200Response) GetDataOk() (*ManageBypass200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ManageBypass200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given ManageBypass200ResponseData and assigns it to the Data field.
func (o *ManageBypass200Response) SetData(v ManageBypass200ResponseData) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *ManageBypass200Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ManageBypass200Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *ManageBypass200Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *ManageBypass200Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o ManageBypass200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ManageBypass200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableManageBypass200Response struct {
	value *ManageBypass200Response
	isSet bool
}

func (v NullableManageBypass200Response) Get() *ManageBypass200Response {
	return v.value
}

func (v *NullableManageBypass200Response) Set(val *ManageBypass200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableManageBypass200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableManageBypass200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableManageBypass200Response(val *ManageBypass200Response) *NullableManageBypass200Response {
	return &NullableManageBypass200Response{value: val, isSet: true}
}

func (v NullableManageBypass200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableManageBypass200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


