/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreatePlan201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreatePlan201Response{}

// CreatePlan201Response struct for CreatePlan201Response
type CreatePlan201Response struct {
	Success *bool `json:"success,omitempty"`
	Data *Plan `json:"data,omitempty"`
	RequestId *string `json:"requestId,omitempty"`
}

// NewCreatePlan201Response instantiates a new CreatePlan201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreatePlan201Response() *CreatePlan201Response {
	this := CreatePlan201Response{}
	return &this
}

// NewCreatePlan201ResponseWithDefaults instantiates a new CreatePlan201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreatePlan201ResponseWithDefaults() *CreatePlan201Response {
	this := CreatePlan201Response{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *CreatePlan201Response) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlan201Response) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *CreatePlan201Response) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *CreatePlan201Response) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreatePlan201Response) GetData() Plan {
	if o == nil || IsNil(o.Data) {
		var ret Plan
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlan201Response) GetDataOk() (*Plan, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreatePlan201Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Plan and assigns it to the Data field.
func (o *CreatePlan201Response) SetData(v Plan) {
	o.Data = &v
}

// GetRequestId returns the RequestId field value if set, zero value otherwise.
func (o *CreatePlan201Response) GetRequestId() string {
	if o == nil || IsNil(o.RequestId) {
		var ret string
		return ret
	}
	return *o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreatePlan201Response) GetRequestIdOk() (*string, bool) {
	if o == nil || IsNil(o.RequestId) {
		return nil, false
	}
	return o.RequestId, true
}

// HasRequestId returns a boolean if a field has been set.
func (o *CreatePlan201Response) HasRequestId() bool {
	if o != nil && !IsNil(o.RequestId) {
		return true
	}

	return false
}

// SetRequestId gets a reference to the given string and assigns it to the RequestId field.
func (o *CreatePlan201Response) SetRequestId(v string) {
	o.RequestId = &v
}

func (o CreatePlan201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreatePlan201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.RequestId) {
		toSerialize["requestId"] = o.RequestId
	}
	return toSerialize, nil
}

type NullableCreatePlan201Response struct {
	value *CreatePlan201Response
	isSet bool
}

func (v NullableCreatePlan201Response) Get() *CreatePlan201Response {
	return v.value
}

func (v *NullableCreatePlan201Response) Set(val *CreatePlan201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreatePlan201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreatePlan201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreatePlan201Response(val *CreatePlan201Response) *NullableCreatePlan201Response {
	return &NullableCreatePlan201Response{value: val, isSet: true}
}

func (v NullableCreatePlan201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreatePlan201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


