/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SetCustomRateLimitsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetCustomRateLimitsRequest{}

// SetCustomRateLimitsRequest struct for SetCustomRateLimitsRequest
type SetCustomRateLimitsRequest struct {
	ApiKey string `json:"apiKey"`
	Limits *SetCustomRateLimitsRequestLimits `json:"limits,omitempty"`
}

type _SetCustomRateLimitsRequest SetCustomRateLimitsRequest

// NewSetCustomRateLimitsRequest instantiates a new SetCustomRateLimitsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetCustomRateLimitsRequest(apiKey string) *SetCustomRateLimitsRequest {
	this := SetCustomRateLimitsRequest{}
	this.ApiKey = apiKey
	return &this
}

// NewSetCustomRateLimitsRequestWithDefaults instantiates a new SetCustomRateLimitsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetCustomRateLimitsRequestWithDefaults() *SetCustomRateLimitsRequest {
	this := SetCustomRateLimitsRequest{}
	return &this
}

// GetApiKey returns the ApiKey field value
func (o *SetCustomRateLimitsRequest) GetApiKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiKey
}

// GetApiKeyOk returns a tuple with the ApiKey field value
// and a boolean to check if the value has been set.
func (o *SetCustomRateLimitsRequest) GetApiKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiKey, true
}

// SetApiKey sets field value
func (o *SetCustomRateLimitsRequest) SetApiKey(v string) {
	o.ApiKey = v
}

// GetLimits returns the Limits field value if set, zero value otherwise.
func (o *SetCustomRateLimitsRequest) GetLimits() SetCustomRateLimitsRequestLimits {
	if o == nil || IsNil(o.Limits) {
		var ret SetCustomRateLimitsRequestLimits
		return ret
	}
	return *o.Limits
}

// GetLimitsOk returns a tuple with the Limits field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SetCustomRateLimitsRequest) GetLimitsOk() (*SetCustomRateLimitsRequestLimits, bool) {
	if o == nil || IsNil(o.Limits) {
		return nil, false
	}
	return o.Limits, true
}

// HasLimits returns a boolean if a field has been set.
func (o *SetCustomRateLimitsRequest) HasLimits() bool {
	if o != nil && !IsNil(o.Limits) {
		return true
	}

	return false
}

// SetLimits gets a reference to the given SetCustomRateLimitsRequestLimits and assigns it to the Limits field.
func (o *SetCustomRateLimitsRequest) SetLimits(v SetCustomRateLimitsRequestLimits) {
	o.Limits = &v
}

func (o SetCustomRateLimitsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetCustomRateLimitsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiKey"] = o.ApiKey
	if !IsNil(o.Limits) {
		toSerialize["limits"] = o.Limits
	}
	return toSerialize, nil
}

func (o *SetCustomRateLimitsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetCustomRateLimitsRequest := _SetCustomRateLimitsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSetCustomRateLimitsRequest)

	if err != nil {
		return err
	}

	*o = SetCustomRateLimitsRequest(varSetCustomRateLimitsRequest)

	return err
}

type NullableSetCustomRateLimitsRequest struct {
	value *SetCustomRateLimitsRequest
	isSet bool
}

func (v NullableSetCustomRateLimitsRequest) Get() *SetCustomRateLimitsRequest {
	return v.value
}

func (v *NullableSetCustomRateLimitsRequest) Set(val *SetCustomRateLimitsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSetCustomRateLimitsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSetCustomRateLimitsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetCustomRateLimitsRequest(val *SetCustomRateLimitsRequest) *NullableSetCustomRateLimitsRequest {
	return &NullableSetCustomRateLimitsRequest{value: val, isSet: true}
}

func (v NullableSetCustomRateLimitsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetCustomRateLimitsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


