/*
SubTrackr API

Subscription management platform API

API version: 1.0.0
Contact: support@subtrackr.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PlanInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlanInput{}

// PlanInput struct for PlanInput
type PlanInput struct {
	Name string `json:"name"`
	Price float32 `json:"price"`
	Currency string `json:"currency"`
	BillingCycle string `json:"billingCycle"`
	Features []string `json:"features,omitempty"`
}

type _PlanInput PlanInput

// NewPlanInput instantiates a new PlanInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlanInput(name string, price float32, currency string, billingCycle string) *PlanInput {
	this := PlanInput{}
	this.Name = name
	this.Price = price
	this.Currency = currency
	this.BillingCycle = billingCycle
	return &this
}

// NewPlanInputWithDefaults instantiates a new PlanInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlanInputWithDefaults() *PlanInput {
	this := PlanInput{}
	return &this
}

// GetName returns the Name field value
func (o *PlanInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PlanInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PlanInput) SetName(v string) {
	o.Name = v
}

// GetPrice returns the Price field value
func (o *PlanInput) GetPrice() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Price
}

// GetPriceOk returns a tuple with the Price field value
// and a boolean to check if the value has been set.
func (o *PlanInput) GetPriceOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Price, true
}

// SetPrice sets field value
func (o *PlanInput) SetPrice(v float32) {
	o.Price = v
}

// GetCurrency returns the Currency field value
func (o *PlanInput) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *PlanInput) GetCurrencyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *PlanInput) SetCurrency(v string) {
	o.Currency = v
}

// GetBillingCycle returns the BillingCycle field value
func (o *PlanInput) GetBillingCycle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BillingCycle
}

// GetBillingCycleOk returns a tuple with the BillingCycle field value
// and a boolean to check if the value has been set.
func (o *PlanInput) GetBillingCycleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingCycle, true
}

// SetBillingCycle sets field value
func (o *PlanInput) SetBillingCycle(v string) {
	o.BillingCycle = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *PlanInput) GetFeatures() []string {
	if o == nil || IsNil(o.Features) {
		var ret []string
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PlanInput) GetFeaturesOk() ([]string, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *PlanInput) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given []string and assigns it to the Features field.
func (o *PlanInput) SetFeatures(v []string) {
	o.Features = v
}

func (o PlanInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlanInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["price"] = o.Price
	toSerialize["currency"] = o.Currency
	toSerialize["billingCycle"] = o.BillingCycle
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	return toSerialize, nil
}

func (o *PlanInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"price",
		"currency",
		"billingCycle",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPlanInput := _PlanInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPlanInput)

	if err != nil {
		return err
	}

	*o = PlanInput(varPlanInput)

	return err
}

type NullablePlanInput struct {
	value *PlanInput
	isSet bool
}

func (v NullablePlanInput) Get() *PlanInput {
	return v.value
}

func (v *NullablePlanInput) Set(val *PlanInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePlanInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePlanInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlanInput(val *PlanInput) *NullablePlanInput {
	return &NullablePlanInput{value: val, isSet: true}
}

func (v NullablePlanInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlanInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


