# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from subtrackr_sdk.models.get_rate_limit_analytics200_response_data_by_tier_free import GetRateLimitAnalytics200ResponseDataByTierFREE
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetRateLimitAnalytics200ResponseDataByTier(BaseModel):
    """
    GetRateLimitAnalytics200ResponseDataByTier
    """ # noqa: E501
    free: Optional[GetRateLimitAnalytics200ResponseDataByTierFREE] = Field(default=None, alias="FREE")
    basic: Optional[GetRateLimitAnalytics200ResponseDataByTierFREE] = Field(default=None, alias="BASIC")
    premium: Optional[GetRateLimitAnalytics200ResponseDataByTierFREE] = Field(default=None, alias="PREMIUM")
    enterprise: Optional[GetRateLimitAnalytics200ResponseDataByTierFREE] = Field(default=None, alias="ENTERPRISE")
    __properties: ClassVar[List[str]] = ["FREE", "BASIC", "PREMIUM", "ENTERPRISE"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRateLimitAnalytics200ResponseDataByTier from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of free
        if self.free:
            _dict['FREE'] = self.free.to_dict()
        # override the default output from pydantic by calling `to_dict()` of basic
        if self.basic:
            _dict['BASIC'] = self.basic.to_dict()
        # override the default output from pydantic by calling `to_dict()` of premium
        if self.premium:
            _dict['PREMIUM'] = self.premium.to_dict()
        # override the default output from pydantic by calling `to_dict()` of enterprise
        if self.enterprise:
            _dict['ENTERPRISE'] = self.enterprise.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRateLimitAnalytics200ResponseDataByTier from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "FREE": GetRateLimitAnalytics200ResponseDataByTierFREE.from_dict(obj["FREE"]) if obj.get("FREE") is not None else None,
            "BASIC": GetRateLimitAnalytics200ResponseDataByTierFREE.from_dict(obj["BASIC"]) if obj.get("BASIC") is not None else None,
            "PREMIUM": GetRateLimitAnalytics200ResponseDataByTierFREE.from_dict(obj["PREMIUM"]) if obj.get("PREMIUM") is not None else None,
            "ENTERPRISE": GetRateLimitAnalytics200ResponseDataByTierFREE.from_dict(obj["ENTERPRISE"]) if obj.get("ENTERPRISE") is not None else None
        })
        return _obj


