# coding: utf-8

"""
    SubTrackr API

    Subscription management platform API

    The version of the OpenAPI document: 1.0.0
    Contact: support@subtrackr.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from subtrackr_sdk.models.get_rate_limit_status200_response_data_current import GetRateLimitStatus200ResponseDataCurrent
from subtrackr_sdk.models.get_rate_limit_status200_response_data_limits import GetRateLimitStatus200ResponseDataLimits
from subtrackr_sdk.models.get_rate_limit_status200_response_data_reset_at import GetRateLimitStatus200ResponseDataResetAt
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GetRateLimitStatus200ResponseData(BaseModel):
    """
    GetRateLimitStatus200ResponseData
    """ # noqa: E501
    limits: Optional[GetRateLimitStatus200ResponseDataLimits] = None
    current: Optional[GetRateLimitStatus200ResponseDataCurrent] = None
    remaining: Optional[GetRateLimitStatus200ResponseDataCurrent] = None
    reset_at: Optional[GetRateLimitStatus200ResponseDataResetAt] = Field(default=None, alias="resetAt")
    __properties: ClassVar[List[str]] = ["limits", "current", "remaining", "resetAt"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetRateLimitStatus200ResponseData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of limits
        if self.limits:
            _dict['limits'] = self.limits.to_dict()
        # override the default output from pydantic by calling `to_dict()` of current
        if self.current:
            _dict['current'] = self.current.to_dict()
        # override the default output from pydantic by calling `to_dict()` of remaining
        if self.remaining:
            _dict['remaining'] = self.remaining.to_dict()
        # override the default output from pydantic by calling `to_dict()` of reset_at
        if self.reset_at:
            _dict['resetAt'] = self.reset_at.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetRateLimitStatus200ResponseData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "limits": GetRateLimitStatus200ResponseDataLimits.from_dict(obj["limits"]) if obj.get("limits") is not None else None,
            "current": GetRateLimitStatus200ResponseDataCurrent.from_dict(obj["current"]) if obj.get("current") is not None else None,
            "remaining": GetRateLimitStatus200ResponseDataCurrent.from_dict(obj["remaining"]) if obj.get("remaining") is not None else None,
            "resetAt": GetRateLimitStatus200ResponseDataResetAt.from_dict(obj["resetAt"]) if obj.get("resetAt") is not None else None
        })
        return _obj


